vscode-kubernetes-tools/vscode-kubernetes-tools

- package.json
- src/acs.ts
- src/azure.ts
- src/createcluster.ts
- src/extension.ts
- src/wizard.ts
Addresses https://github.com/Azure/vscode-kubernetes-tools/issues/2.  This implementation includes only creating ACS and AKS clusters, but it should be possible to add other Kubernetes implementations (EKS, GKE, minikube, etc.) over time.  (The code is a bit messy but I'd be happy to work with anyone wanting to contribute such a thing.)
> Add command to create a Kubernetes cluster

- package-lock.json
- package.json
Since npm@5 (nodejs@8 LTS), run `npm install` will automatically generate a package-lock.json file, and the official community suggests us to save it in source control. 
See wiki https://docs.npmjs.com/files/package-lock.json for more info about package-lock.json.
> Format package.json and add package-lock.json file

- .gitignore
- .travis.yml
- gulpfile.js
- package-lock.json
- package.json
- tslint.json
1.  Add gulp script to run tslint check. (Run `gulp tslint` at cmd)
2. Add .travis.yml file 
TODO: 
1. In order to enable travis ci, need one of the repository administrators to activate it on https://travis-ci.org/.
3. After extending tslint latest rules (via ` "extends": "tslint:latest"`), there are many tslint errors in current code, should we need fix them, right?
> Add gulp script and .travis.yml to run tslint/build check

- language-configuration.json
> Fix Helm .yaml comments & introducing block comments for Helm .tpl

- package.json
> :wrench: Add Kubernetes Dashboard to tree-explorer view right click menu

- src/explainer.ts
The Explain command was producing only "Loading..." messages.  It turns out there were a couple of problems:
* The k8s API component was producing base URLs ending in `//` instead of `/`.  The k8s API server was therefore returning a 404 with a list of paths, instead of the `/swagger.json`.
* The k8s Swagger changed to identify resources using `x-kubernetes-group-version-kind` instead of the JSON property name (which is now `io.k8s.lots.of.bits.the-resource-name`).
This PR fixes these issues so that Explain works again.
> Fixes to make hover tips work with new k8s Swagger

- README.md
- package.json
- src/debug/debugSession.ts
- src/debug/providerRegistry.ts
- src/extension.ts
Enable java debugging support in the extension. For node debugging enhancement, we'd like to invite node experience team to help improve it.
> Enable java debugging support

- snippets/helm.json
> Fix Helm if-else if-else syntax

- src/extension.ts
- src/kuberesources.ts
> When doing a Get for the resource open in the editor, use the terminal

- src/extension.ts
When `docker push` failed during a Kubernetes Run command, we would just say "Image push failed" and dump standard error.  The Docker error often did not help users to understand what the problem might be.  This PR checks for known messages and suggests possible remediations (e.g. user id not configured, user not logged in to Docker).
Fixes #77.
> Better error messages if docker push fails during Run

- src/extension.ts
Per issue https://github.com/Azure/vscode-kubernetes-tools/issues/106, this PR will fix no progress issue for Kubernetes: Create command.
> Add progress bar for Kubernetes: Create/Apply commands

- src/extension.ts
> Add progress bar for more commands Expose/Scale/Run

- src/components/clusterprovider/azure/azure.ts
> Remove Basic SKUs from ACS/AKS create cluster agent size list

- src/extension.ts
- src/helm.exec.ts
- src/hostutils.ts
> Meaningful error if user tries to create Helm chart when no folder open

- src/extension.ts
> For Delete command, don't try to get resource from active document

- src/components/clusterprovider/azure/azure.ts
- src/components/clusterprovider/azure/azureclusterprovider.ts
- src/wizard.ts
> Reduce likelihood of spurious cluster creation failure messages

- src/components/clusterprovider/azure/azureclusterprovider.ts
> After adding cluster, refresh Explorer to show it

- src/explorer.ts
- src/kuberesources.ts
Hi I just tested ingress support - worked locally. Sorry for the whitespace changes - VSCode forced me to clean things up
> Adding ingress support

- src/extension.ts
> More meaningful error messages if no document open or not JSON or YAML

- snippets/pod.yaml
add pod snippet 
https://github.com/Azure/vscode-kubernetes-tools/issues/42
> add pod snippet.

- schema/schema_enums-v1.9.3.json
- src/yaml-support/yaml-constant.ts
- src/yaml-support/yaml-schema.ts
kind, apiVersion is not included
> add enums for properties

- .vscode/launch.json
- .vscode/tasks.json
- package.json
Changes:
- Update tasks.json to `2.0.0` schema version
- Update launch.json to `0.2.0` schema version
Fixes: https://github.com/Azure/vscode-kubernetes-tools/issues/157
> Updated tasks.json/launch.json to 2.0.0/0.2.0

- README.md
- package.json
- Removed notes to install helm-template plugin
- Removed requirement notes in package.json
Fixes: https://github.com/Azure/vscode-kubernetes-tools/issues/145
> Remove helm-template Requirements

- src/extension.ts
- src/kube.documentProvider.ts
Signed-off-by: andxu <andxu@microsoft.com>
> provide json content for kubernetes resources other than opening a new file

- src/components/clusterprovider/azure/azure.ts
- src/components/clusterprovider/azure/azureclusterprovider.ts
Fixes #143, which rendered the wrong copy when configuring an existing cluster.
> Fixing configure from cluster copy

- package.json
- src/configMap.ts
- src/explorer.ts
- src/extension.ts
- src/kubectlUtils.ts
> Add browsing of ConfigMaps and Secrets to the tree explorer.

- package-lock.json
- package.json
> Upgrading hoek version to 4.2.1 and updating vscode dev dependency

- package.json
- src/configMap.ts
- src/explorer.ts
- src/extension.ts
@itowlson @bnookala @testforstephen
> Add the ability to add configs or secrets from files.

- schema/swagger-v1.9.3.json
Fix bug https://github.com/Azure/vscode-kubernetes-tools/issues/175
Before:
Now:
> Bug #175: Add the missing 'type' key for object value property to fix the validation issue

- src/components/kubectl/port-forward.ts
- src/extension.ts
Based on the pointers and feedback on the issue here is an attempt to fix the problem. 
Please let me know if I have missed anything.
> Fix for #231

- src/components/clusterprovider/azure/azure.ts
- src/components/clusterprovider/azure/azureclusterprovider.ts
> Azure Kubernetes Service (AKS) GA

- README.md
- package.json
- src/extension.ts
- This is the initial version for the ability to follow/tail logs (#235). 
- Opening an PR for gather early feedback. 
- I have tried to keep it as DRY as possible. 
- Had to abandon #237 because of an rebase issue. (my git knowledge failed me 😅 sorry about that)
> WIP: Support Show/Follow for Kubernetes Container Logs

- README.md
- src/extension.ts
Fixing documentation and linting.
> Fixing documentation and linting from #239

- package.json
- src/configMap.ts
> Don't allow Add File and Delete File to be invoked from palette

- .editorconfig
Adds an .editorconfig. Thanks for noting we didn't have one, @shreyu86!
> Adding .editorconfig for fun and profit

- src/explorer.ts
- src/kubectlUtils.ts
@itowlson this mostly works, but selecting the pods doesn't work correctly. I see the virtual FS that does this, but I don't know how it is triggered, so I don't know how to pass the right namespace along...
> Add node expansion and listing of pods for nodes.

- src/explorer.ts
- src/extension.ts
- src/kuberesources.virtualfs.ts
> Load correctly when tree item is not in active namespace

- package.json
- src/components/clusterprovider/azure/azureclusterprovider.ts
- src/components/clusterprovider/common/explorer.ts
- src/components/clusterprovider/common/form.ts
- src/components/clusterprovider/minikube/minikube.ts
- src/components/clusterprovider/minikube/minikubeclusterprovider.ts
- src/explorer.ts
- src/extension.ts
@bnookala @itowlson 
Pretty simple for now, but we can expand from here.
> Add support for minikube clusters.

- package.json
- src/extension.ts
- src/kubeNamespace.ts
This implements and resolves Issue #265 , wherein now the Namespace command is available via the Context menu in explorer as well as via command palette.
Signed-off-by: Kamesh Sampath <kamesh.sampath@hotmail.com>
> Implementation of Kubernetes: set namespace command

- src/kubectlUtils.ts
Handling case of no resources, ref: https://github.com/Azure/vscode-kubernetes-tools/pull/277#discussion_r200506926
> Handling the case of no resources, bugfix for #272

- CHANGELOG.md
- package-lock.json
- package.json
Codenamed either "Petulant Scorpionfish" or "One Louder", depending on who you talk to.  @squillace
> Publish version 0.1.11

- src/draft/draft.ts
- src/extension.ts
Fixes a couple of things:
1. If the project had charts but didn't have a draft.toml, Draft Create would fail because the charts directory already existed (as per the Draft CLI).  This was inconvenient for DevOps projects which were eminently draftable but had their TOMLs removed because they were also used for DevSpaces - which _doesn't_ use Draft and didn't want to confuse non-Draft users with Draft files.  So now if draft.toml doesn't exist then we create it in the extension.  (Workaround until Draft issue https://github.com/Azure/draft/issues/219 fixes it in the CLI.)
2. Draft reorganised the packs so there were all under a `github.com` directory.  This fouled up the extension's pack discovery mechanism.  We now lean on the `draft pack list` command, and do some sanitising to produce a …
> Fixes for Draft Create command

- README.md
- package.json
- src/extension.ts
- src/helm.exec.ts
This PR adds the ability to package helm chart through vscode
> add support for helm package

- README.md
Documents the undocumented, fixes #280
> Fast forward readme

- src/components/clusterprovider/minikube/minikube.ts
- src/components/clusterprovider/minikube/minikubeclusterprovider.ts
- src/extension.ts
> Add an option for VM driver as well as additional flags.

- src/explorer.ts
- src/kuberesources.linkprovider.ts
- src/kuberesources.ts
Fixes #343, except for showing the jobs created by a cron job, which is currently looking a bit tricky.
> Show cron jobs in tree view

- src/components/clusterprovider/minikube/minikube.ts
> Add status bar notifications for starting, running and stopping minikube

- src/extension.ts
In the process of working on hover, I noticed that many promises weren't handling errors.
Next step would be to switch to async/await
> Add error handling to many promises.

- buildsnippets/snippets.go
- snippets/helm.json
This PR fixes a typo with Service snippet
> change kindSerice to kindService

- README.md
- package.json
- src/components/clusterprovider/minikube/minikube.ts
- src/components/config/config.ts
- src/components/installer/installer.ts
- src/draft/draft.ts
- src/helm.exec.ts
- src/kubectl.ts
- src/shell.ts
> Per-OS override of tool paths

- .travis.yml
> Nail down Node version so CI doesn't break

- src/helm.exec.ts
> Fix for Helm Package using a URL string instead of folder path

- package-lock.json
- package.json
- src/components/clusterprovider/minikube/minikube.ts
- src/components/installer/installer.ts
- src/extension.ts
- src/kubectl.ts
- test/kubectl.test.ts
> Add an upgrade check for minikube, also some cleanups.

- src/explorer.ts
- src/kuberesources.ts
Closes #407
@itowlson @squillace please take a look as it changes the tree-view UX slightly.
> Add browse for endpoints, group in a 'network' item.

- src/components/clusterprovider/minikube/minikube.ts
> Fix spurious Minikube update-check parse error on Windows

- src/binutil.ts
- src/components/config/config.ts
- src/components/installer/installer.ts
- src/draft/draft.ts
- src/explainer.ts
- src/extension.ts
- src/helm.documentProvider.ts
- src/helm.exec.ts
- src/helm.repoExplorer.ts
- src/helm.resources.ts
- src/kubectl.ts
- src/shell.ts
- src/wsl-fs.ts
> Add support for using the kubernetes extension on Windows via WSL kubectl/helm

- README.md
> adding instructions to readme for skip tls verifiy

- src/explorer.ts
- src/kuberesources.objectmodel.ts
- src/kuberesources.ts
@itowlson 
The discussion began in #377 but moved here so we can discuss it independent of the other work in that PR.
I'm open to alternate UX, but I couldn't think of a good alternative, and I do think it's gooid to give people a really rapid way to get system status via the GUI.
> Make Pod Status viewable in the Tree VIew

- package-lock.json
- package.json
We're seeing intermittent IDE errors since importing the `@kubernetes/node-client` package.  These are probably VS Code being silly, as everything appears to work okay, but I'm going to update the request package types anyway.
> Update @types/request package

- README.md
This addresses airgapped scenarios.
Fixes #415.
cc @EranIsraeli
> Added info about installing from VSIX

- src/explorer.ts
- src/kubectlUtils.ts
- src/kuberesources.objectmodel.ts
- src/kuberesources.ts
Fixes #431 
thanks @itowlson for the awesome guidance!
> CRD implementation

- src/explorer.ts
> Fix duplicate Services and Ingress folders in tree

- README.md
- src/components/clusterprovider/azure/azureclusterprovider.ts
Send telemetry when create and add cluster
> Send telemetry when create and add cluster

- src/components/clusterprovider/azure/azure.ts
> Rework Azure CLI version regex to be compatible with 2.0.58

- package-lock.json
- src/components/describe/describeWebview.ts
- src/components/kubectl/logs.ts
- src/components/logs/logsWebview.ts
- src/components/webpanel/webpanel.ts
@itowlson 
This adds a webview based log viewer. It adds 4 capabilities:
* Filter matches
* Hide matches
* Show logs that follow match
* Show logs that preceed match
Here's some screenshots to show how it works...
No filtering:
Matches `/health`
Hides `/health`
Logs after a specific date:
> Add a HTML5-based logview

- README.md
- package.json
- src/components/clusterprovider/minikube/minikube.ts
- src/components/config/config.ts
#481  
Went with `vsminikube` for consistency with `vsdocker` config option
lmk!
> Suppress minikube upgrade check

- src/components/kubectl/port-forward.ts
> Add logic to load and suggest ports from the container.

- src/components/kubectl/autoversion.ts
- src/fs.ts
> Fix for autoversioned kubectl not being executable on Unix

- .vscodeignore
- docs/README.md
- docs/extending/README.md
- docs/extending/clusterprovider.md
- docs/extending/samples/clusterprovider/contosocloud.ts
- src/api/contract/api.ts
- src/api/contract/clusterprovider/v1.ts
- src/api/contract/kubectl/v1.ts
- src/api/implementation/apibroker.ts
- src/api/implementation/apiutils.ts
- src/api/implementation/clusterprovider/v1.ts
- src/api/implementation/clusterprovider/versions.ts
- src/api/implementation/kubectl/v1.ts
- src/api/implementation/kubectl/versions.ts
- src/components/clusterprovider/clusterproviderregistry.ts
- src/extension.ts
- tsconfig.json
A reworked proposal for an API design.
> API proposal

- src/components/kubectl/dashboard.ts
- src/components/platform/browser.ts
- src/components/platform/clipboard.ts
- src/debug/debugSession.ts
- src/extension.ts
> Update to use native vscode apis.

- src/components/clusterprovider/azure/azure.ts
> Update AKS region list to all the new places

- package.json
- src/components/describe/describeWebview.ts
- src/extension.ts
> Add a refresh button for 'describe'

- src/helm.repoExplorer.ts
See #510 for demonstration of the problem.  This PR looks for lines in the Helm output that must be continuations of descriptions from previous lines, and merges them into the appropriate description.
Fixes #510.
> Fix for embedded newlines in chart descriptions

- docs/extending/clusterexplorer.md
- docs/extending/clusterexplorernodes.md
- docs/extending/clusterexplorerui.md
- src/api/contract/cluster-explorer/v1.ts
- src/api/implementation/cluster-explorer/v1.ts
- src/explorer.extension.ts
- src/explorer.ts
- src/utils/providerresult.ts
API for modifying existing tree nodes (as opposed to creating entirely new ones).
> Cluster explorer UI customisation

- README.md
- package.json
> Improve/update docs.

- CHANGELOG.md
- package-lock.json
- package.json
Nothing interesting in this PR per se, but putting it out for review so that folks can check the issue queue etc. and flag if they think anything is critical to address before GA.
@brendandburns reordered the keywords for now - see #534 for why, and can refine after GA if need be.
> Publish 1.0.0

- package-lock.json
- package.json
- src/components/kubectl/port-forward.ts
Closes #525
cc @bnookala @itowlson
> Add port forwarding for services and deployments.

- package.json
> Reduce keywords to 5

- package-lock.json
- package.json
> Chore: Update dependencies.

- package.json
> switch onDebug to onDebugResolve:draft

- src/components/clusterprovider/azure/azure.ts
> Detect Azure CLI even if it writes to stderr

- src/components/kubectl/logs.ts
- src/components/logs/logsWebview.ts
- src/kubectl.ts
- src/shell.ts
> Add web view support for follow logs.

- package.json
- src/extension.ts
- src/kuberesources.ts
> Add scale to right-click of scaleable resources

- src/configMap.ts
To display values out of secrets and config maps, we stuff the base64-encoded value and its name into a URL, then the document provider extracts the value by taking the first chunk of the URL path.  Unfortunately, base64 encoding allows `/` as a character in the encoded string.  When we naively split the URL path to retrieve the value, if it contained a `/`, we get the truncated portion up to the `/`.
Frustratingly, VS Code's `Uri.parse` function is clever enough to spot URI-encoded characters and 'helpfully' decode them, so the obvious fix of encoding the base64 string does not work.  My proposed workaround is to instead encode as `hex`, which is inefficient, but is built in and is extremely safe.  A more efficient solution could be achieved by bringing in a base32 encoding package, or …
> Fix config value display truncation

- src/yaml-support/yaml-schema.ts
> Fix 'no schema content' error on CRD instances with no schema

- src/helm.documentProvider.ts
> Fix empty preview of NOTES.txt

- src/helm.exec.ts
- src/helm.repoExplorer.ts
So far, fixes for the Helm Version command and for the repo explorer erroring when displaying the charts in a repo.  Still needs more testing in case anything else has breaking changes.
> Helm 3 compatibility

- src/helm.documentProvider.ts
Because `-x` no longer works.  Longer term, we'll figure out what we want this to do, but for now, just give a graceful error.
> Disable Template Preview command for Helm 3

- rawsnippets/deployment.yaml
Hope this will fix  Deployments to apiVersion: apps/v1
> change apiVersion for Deployment to apps/v1

- src/components/clusterprovider/minikube/minikube.ts
> Fix minikube upgrade check 

- package.json
- src/helm.exec.ts
I think this is the last tranche of Helm 3 compatibility updates unless anything changes in the final betas... all seems to work (except Template Preview which Helm 3 does not support, but we provide an informative message explaining this).
> Helm 3 compatibility updates

- language-configuration.json
> fix auto closing pairs issue

- src/yaml-support/schema-holder.ts
In the fallback schema baked into the extension, the Kubernetes IntOrString type has the following definition:
```        "io.k8s.apimachinery.pkg.util.intstr.IntOrString": {
"oneOf": [
{
"type": "string"
},
{
"type": "integer"
}
]
}
```
This works great!  Unfortunately, it's _not_ how Kubernetes now defines IntOrString in its latest and greatest Swagger documents.  Instead, it defines it like this:
```
"io.k8s.apimachinery.pkg.util.intstr.IntOrString": {
"description": "IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number.",
"format": "int-or-string",
"type": "string"
}
```
This does _not_ work …
> Fix YAML warning on numeric IntOrString values

- src/helm.authoring.ts
- src/helm.symbolProvider.ts
- src/utils/cancellation.ts
> Helm parameterisation fixes

- src/components/kubectl/kubeconfig.ts
> Fix Merge to Kubeconfig command if no kubeconfig file

- CONTRIBUTING.md
Adds a section about committers. Describes types of contributions with more details.
> add committers section

- src/components/kubectl/logs.ts
- src/components/logs/logsWebview.ts
- src/components/webpanel/webpanel.ts
This PR addresses a couple of issues i found with the logPanel. First is #725. Second is related to the listener created to append new content when following logs. The process created was never killed.
> fixed disposed error logpanel + kill useless process

- src/components/logs/logsWebview.ts
This is related to #683.
No filters were applied when new logs were appended. I found a `TODO: need to apply filters here` so i guess it was already planned but it was left uncomplete
> Apply filters when new logs are appended by using Follow Logs

- src/api/contract/cluster-explorer/v1_1.ts
- src/api/implementation/cluster-explorer/v1_1.ts
- src/api/implementation/cluster-explorer/versions.ts
Fixes an eslint warning on these two files.
> Don't emit a camelCase warning for V1_1

- src/api/contract/cluster-explorer/v1_1.ts
- src/components/clusterexplorer/node.folder.resource.ts
- src/components/clusterexplorer/node.resource.ts
- src/components/clusterexplorer/node.ts
- src/kubectlUtils.ts
- src/kuberesources.objectmodel.ts
> Always provide metadata on ClusterExplorerResourceNode

- src/extension.ts
Fixes #741.  
See also https://github.com/microsoft/vscode/issues/94872
> Work around VS Code passing odd object to panel title commands

- src/components/clusterprovider/minikube/minikube.ts
> Fixed issue with host item when checking minikube status

- src/helm.documentProvider.ts
> fixed preview template with helm 3

- src/extension.ts
- src/helm.repoExplorer.ts
> added HelmError node click handler to show additional details

- src/components/logs/logsWebview.ts
Signed-off-by: bfitzpat@redhat.com <bfitzpat@redhat.com>
> issue #593 - adding simple auto-scroll checkbox to enable and disable

- src/binutil.ts
> fix issue with terminal shell path (#781)

- src/outputUtils.ts
> Changed way values are extracted from output separated by whitespaces

- src/components/clusterexplorer/resourceui.ts
> List pods below jobs nodes

- snippets/configmap.yaml
- snippets/ingress.yaml
- snippets/job.yaml
- snippets/persistentvolume.yaml
- snippets/persistentvolumeclaim.yaml
- snippets/secret.yaml
- snippets/statefulset.yaml
As requested in #816 and #821 this PR adds some new snippets.
> Add new k8s snippets 

- CHANGELOG.md
> Fix 1.2.2 contribution acknowledgments

- README.md
This PR adds example code to illustrate the "disable-linters" setting.
Related to #408
> Add to Linter docs

- src/binutilplusplus.ts
> Fix Follow Logs not working with nondefault kubeconfig

- src/outputUtils.ts
> Fix node pods having wrong names and namespaces

- src/helm.exec.ts
- src/kuberesources.linkprovider.ts
- src/kuberesources.virtualfs.ts
> Clicking Helm History node now loads the specified revision

- src/components/clusterexplorer/node.helmrelease.ts
- src/components/clusterexplorer/node.ts
- src/helm.exec.ts
Fixes #881.
This has the info as a tooltip - is that going to work for you @cforce?  If not let's discuss good ways of presenting this extra info.
cc @shreyaskarnik as I don't seem to be able to add you as a reviewer
> Show chart and app version in Helm release history

- src/components/installer/installationlayout.ts
- src/components/installer/installer.ts
- src/components/kubectl/autoversion.ts
> fix install dependencies is hardcoded to amd64

- snippets/ingress.yaml
> Updated ingress.yml snippet to use networking.k8s.io/v1

- package.json
- src/components/logs/app/index.html
Based on your comment https://github.com/Azure/vscode-kubernetes-tools/pull/933#issuecomment-828946641 I added everything in one PR but i actually just copied your stuff for the package.json. It worked fine.
The missing piece was the broken css. Still not sure why it stops working after packaging it. I'll investigate on it when i have time but this should fix our issue for the moment
> Fix logs view css + webpack 

- package-lock.json
- package.json
Hi maintainers! I'm vscode-kubernetes-tools and I work at [Bison Trails](https://bisontrails.co/). We're doing an internal hackathon this week.
Our team loves vscode-kubernetes-tools, but it got flagged during a recent security review. Our team voted to use our hackathon time to patch vulnerabilities in our favorite OSS tools and specifically to try to get vscode-kubernetes-tools approved for usage within our organization. 
- updated package version which are free from vulnerability
- dependencies forced to vulnerability-free versions when intermediate dependencies are not patched
These changes should improve vscode-kubernetes-tools's security posture. We identified these vulnerabilities using [Salus](https://github.com/coinbase/salus) and the [OSSF …
> security fixes npm part

- package-lock.json
- package.json
- src/components/kubectl/watch.ts
@ivolzhevbt This is the proposal I alluded to in my comment on #963 - it addresses all `npm audit --production` issues but does not try to remediate the `gulp` issues as they cause problems for the `vsce` packager.
> Fix packaging issue

- src/components/clusterexplorer/resourcekinds/resourcekinds.configuration.ts
- src/kubectlUtils.ts
- src/kuberesources.objectmodel.ts
it resolves #968 
Example of performances below. Quite fast.
@teamtitangithub could you please verify it solves your issue? Thanks
> fix issue when displaying many large secrets on tree (#968)

- README.md
- src/yaml-support/consideration-filter.ts
- src/yaml-support/yaml-schema.ts
- test/suite/yaml-consideration-filter.test.ts
Fixes #995.
@lstocchi @rille111 would you be able to give this a bit of a real world test?  I've written unit tests but due to recent shenanigans I'm not in a position to test in a real setup right now.  Thanks and sorry for being so half-baked!
> Allow user to exclude YAML file from processing

- recommendation/recommended-tags.json
fixes #985
might be better to wait merge in main branch and a release for at least one of the extension:
* https://github.com/camel-tooling/camel-lsp-client-vscode/pull/830
* https://github.com/camel-tooling/vscode-camel-extension-pack/pull/58
* https://github.com/camel-tooling/vscode-camelk/pull/971
I took the key of the CRD from: https://camel.apache.org/camel-k/1.7.x/apis/camel.html
> Add Camel Yaml in recommended tags

- src/components/kubectl/port-forward.ts
It seems like some checks are not running in PR builds, which resulted in the port forwarding changes hitting TypeScript `undefined`-safety checks in the main build.  This PR adds `undefined` handling; longer term of course we need to align the two builds so that PR authors don't get bitten by this.
@paroga Would you be able to check that my changes look okay please?  My guess is that in reality these things will never actually be undefined so this is purely to satisfy the type checker, but if you could confirm that I haven't broken anything on the happy path then that would be great.  Thanks!  (And sorry for the glitch in the build system.)
> Fix TypeScript undefined checks

- CHANGELOG.md
- package.json
Since everybody has been nice this year 🎅
> Publish 1.3.5

- README.md
- package.json
- src/components/config/config.ts
- src/kubectl.ts
> Allow user to suppress warning if no kubectl binary

- buildsnippets/snippets.go
- snippets/hpa.yaml
Hello,
Thank you for maintaining this great extension!
I'm adding a snippet for HPA. I hope I'm not missing, or breaking anything :)
> Add HPA snippet

- README.md
- package.json
- src/components/config/config.ts
- src/components/recommender/extension-recommender.ts
> Use custom setting to silence extension recommendation notifications (#1053)

- .vscode/extensions.json
- debug-on-kubernetes.md
- package-lock.json
- src/components/logs/app/index.html
- src/components/logs/app/main.js
This list is anything that actually changes the end-user-experience with the extension.
* In the log viewer, changes the default option for `since-input` to `-1` and `since-select` to `s`. (This stills results in `getSinceDuration()` returning `0` by default because of `sinceInput <= 0`.)
* Removes the empty string ('') option for `since-select`. (Now users only have to complete one field instead of 2 if they want to get log history i.e. `select-since` of `3600` for past hour. They can still do both if they want to, i.e. `1` and `hour`.)
* Changes the input type of `since-input` and `tail-input` to `number`. (So now users can't type arbitrary text in them.
I won't get to benefit from the above ideally, since my other PR(s) will add settings to configure default values by default anyway …
> chores: refactor methods, edit configs, fix formatting, etc

- snippets/hpa.yaml
> fix snippet which break intellisense in 1.3.8

- CHANGELOG.md
- package.json
@lstocchi this is primarily to get the Intellisense fix out (I saw you fielded another issue about it, thanks!) - if there are other PRs you want to get in then no worries
> Publish 1.3.9

- snippets/persistentvolume.yaml
- snippets/persistentvolumeclaim.yaml
Fixed some snippets placeholders that were missing the `$` (dollar sign) symbol
> Fix snippets placeholders

- README.md
Signed-off-by: Ben Bodenmiller <bbodenmiller@gmail.com>
> Github -> GitHub

- src/components/logs/logsWebview.ts
> fix: use asWebviewUri to convert webview scripts path

- CHANGELOG.md
- README.md
- package.json
Thank you so much all ❤️☕️🙏🎊 here is the publish PR for this repo, please guide in case I missed anything. Thank you in advance to all the contributors and fyi: @lstocchi , @squillace, @itowlson or other contributors. Thank you so much.
> Changes to publish 1.3.11

- src/components/logs/app/main.js
> Fix logs webview jumps back when scrolling up (#1113)

- README.md
- package-lock.json
- package.json
- src/components/config/config.ts
- src/components/kubectl/namespace.ts
- src/extension.ts
> extend minimal workflow to other commands (get, expose, scale, delete…)

- images/completedPod.svg
- images/notReadyPod.svg
- src/components/clusterexplorer/resourcekinds/resourcekind.pod.ts
- src/kubectlUtils.ts
This is in reference to feature request #1127.  Not ready pods are yellow and completed pods are black.
> added notReady and completed pod status

- README.md
- package.json
- src/components/config/config.ts
- src/helm.exec.ts
> feat: add setting to suppress helm not found warning (#1175)

- CHANGELOG.md
- package-lock.json
- package.json
Thank you so much all ❤️☕️🙏🎊 here is the publish PR for this repo, please guide in case I missed anything. Thank you in advance to all the contributors and fyi: @lstocchi , @squillace, @itowlson or other contributors. Thank you so much.
> Changes to publish 1.3.12

- CHANGELOG.md
- package-lock.json
- package.json
Thank you so much all ❤️☕️🙏🎊 here is the publish PR for this repo, please guide in case I missed anything. Thank you in advance to all the contributors and fyi: @lstocchi , @squillace, @itowlson or other contributors. Thank you so much.
> Changes to publish 1.3.13

- CHANGELOG.md
- package-lock.json
- package.json
Thank you so much all ❤️☕️🙏🎊 here is the publish PR for this repo, please guide in case I missed anything. Thank you in advance to all the contributors and fyi for release approval:  cc: @mikeseese , @michaellzc, @mfilipe-te, @peterbom , @lstocchi fyi @gambtho and @squillace,  or other contributors.
> Publish changes for release.

- package.json
This PR takes care of details post test fixes under #1242  and now take care of `sign-offs` for #1232 
Hence an fyi to @timheuer and thank you so much to https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1232 - a gentle ping as fyi and your contribution is cherry-picked hence it will be maintained against this repo. ❤️☕️🙏
Thank you again and gentle - ❤️🙏 cc: @squillace , @gambtho and @peterbom for eye balling, there is whole lot of dependency update needed which I will align next.
> Hide convert context menu

- CHANGELOG.md
- package-lock.json
- package.json
- test/runTest.ts
This PR is to release a good release pre-package updates work which will take more detailed approach and improve and sanitise for quality. We also need further discussion for helm features or approaches as most of the current open issues are helm related. Currently I am only engineering working towards this repo amongst few hence the slowness. Thanks. 
Note: attempt is to get to the state how we have `aks-vscode-tools` as one of the very updated for various kind of scanning, surely this will take time and I hope with proper interval I can continue the contributions. Thanks all readers. 🙏☕️
Intent behind this is to release whatever we have as one release before package updates et. al. Since at the moment I am the only engineer who works for this repo when I get chance on this repo, I plan …
> Publish release 1.3.16

- snippets/replicaset.yaml
Fixes https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/669
> Added snippet for ReplicaSet

- .github/workflows/build-dev.yml
This PR fixes the broken Ubuntu build. Might make it a part of #1276 under same umbrella.
Sample Run of this Fix against my fork is here: https://github.com/Tatsinnit/vscode-kubernetes-tools/actions/runs/9833761662/job/27144491500?pr=12
Thanks heaps. ❤️🙏 fyi : @squillace , @hsubramanianaks , @qpetraroia  fyi @gambtho
> Fix the ubuntu failure.

- webpack.config.js
This PR fixes webpack warnings/errors
> Fix for webpack errors/warnings

- package-lock.json
- package.json
Hiya all, This PR fixes the issue which will be cause by #1308 because the engine is also need to be same version as dev dependencies on types/vscode.
Thanks heaps all, cc: @squillace , @qpetraroia or @hsubramanianaks
> Fix vscode update with engine update.

- package-lock.json
- package.json
This will fix #1332 , thanks heaps.
Key thing here is that with `vscode` package version we need to update the engine as well.
> Fix vscod eupdate with engine update dependabot.

- package-lock.json
- package.json
Hi Everyone,
Thank you all for your continued collaboration and support. ❤️
* Temporary but moving forward - Downgraded this package use to `2.3.0` 
*  **Please try this VSIX**: [vscode-kubernetes-tools-1.3.17-12hari-tats.vsix.zip](https://github.com/user-attachments/files/17319962/vscode-kubernetes-tools-1.3.17-12hari-tats.vsix.zip)
* Long term: Its only used in one file, we can reaccess the use and remove it if not needed, with something simpler or in-house. Under #1357 
Thank you so much for calls and chats and our effort to systematically go through the list of PR's @hsubramanianaks ❤️ <3 and all especially ❤️ @anime-shed , @kejatura-dev, @ReinierCC, Also, an FYI, so suppress work will stay as it is.:  @qpetraroia, @corneliusroemer, @okgolove, @tejhan, @gambtho, @squillace, 
~It seems …
> Fix clipboardy/webpack issue - breaking release 1.3.17

- package-lock.json
- package.json
- src/components/platform/clipboard.ts
- src/extension.ts
This simple implementation is to implement the copy Kubernetes cluster name funcitonliaty.
This also caters the need mentioned in #1357 . I've test this agains my Mac, but sharing the six for folks to give some good check as well please. Thank you so much. ❤️ 
* In order to use this file, don't un-cmpress this, just remove the `.zip` from file extension and that will get you the `vsix` to test, reason being vsix is not allowed to be directly uploaded into GH hence this way to share.
* Here is the six to try it out please: [vscode-kubernetes-tools-1.3.1-testclipboard.vsix.zip](https://github.com/user-attachments/files/17352827/vscode-kubernetes-tools-1.3.1-testclipboard.vsix.zip)
Thanks heaps.
> Simple clipboard implementation.

- package-lock.json
- package.json
This will fix and take care of #1382 , this PR takes care of engine update with it.
thanks heaps.
> Fix the vscode update.

- package-lock.json
- package.json
This PR fixes #1386 , I will make vsix soon and share it here. thanks!
* VSIX here please: 
[vscode-kubernetes-tools-1.3.18-test-client-node-update.vsix.zip](https://github.com/user-attachments/files/17836471/vscode-kubernetes-tools-1.3.18-test-client-node-update.vsix.zip)
> fix the client-node update.

- src/components/logs/app/main.js
Continuation of changes made here: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1294
Fixes: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1373
> Fix:Init container logs not working

- package-lock.json
- package.json
Hiya all, This PR fixes this build break caused by this PR #1414 , because the engine version also needs updation when the package gets updated. Thanks heaps.
> Fix build break.

- OWNERS.md
Hiya everyone! 👋  
This PR updates the `owner.md` file to reflect the current active contributors and collaborators. The intent is to ensure the file accurately represents those actively engaging with and contributing to the project. This small housekeeping update aims to improve clarity for both the existing team and any new contributors looking to join.  
**Why this matters:** 
- Helps maintain transparency about project contributions, ownership and responsibilities.  
- Encourages open collaboration by providing a clear point of contact for contributors.  
- Supports our shared goal of fostering an inclusive and impactful project! 😊  
**Gentle Ping 🚀**  
A big shoutout to **Ralph (@squillace), Reinier (@ReinierCC), Tejhan (@tejhan) , Hari (@hsubramanianaks) , Quentin (@qpetraroia) and …
> Update `owner.md` for Current Active Users and Project Collaboration  

- .github/workflows/codeql.yml
This PR integrates CodeQL, GitHub’s static analysis tool, to enhance security by identifying potential vulnerabilities in the codebase. CodeQL will automatically scan for security issues in pull requests and scheduled workflows, helping to detect common vulnerabilities such as SQL injection, buffer overflows, and other security flaws.  
Following changes add:
- Code QL to GitHub Actions for automated security scanning.  
- Configured scans to run on **push**, **pull requests**, and a **weekly schedule** for continuous monitoring. 
- Improves security by catching vulnerabilities early.  
- Automates code scanning without impacting development velocity.  
- Aligns with best practices for secure software development.  
- [GitHub CodeQL …
> GH Workflow: Add code ql for the repo.

- package-lock.json
- package.json
- src/components/kubectl/dashboard.ts
Hiya, This PR will fix #1458 , things need to be reviewed and tested, might be I will also add vsix. 
Thank you so much ❤️ Opening this as a reference for now, cc: @ReinierCC, @tejhan , @hsubramanianaks ,  also cc:  @squillace
> Fix the type/nodes update.

- OWNERS.md
Thank you so much for new addition in the owners list @bosesuneha and @davidgamero ❤️ 
FYI and cc: @ReinierCC , @tejhan , @squillace and @gambtho
> Owner udpate.

- src/telemetry-helper.ts
This fixes a broken telemetry for this extension to correctly enable the right data.
The term master node was deprecated and there for this change is valid, for further here is more reference to the docs please:
* https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#urgent-upgrade-notes 
* https://kubernetes.io/docs/concepts/overview/components/
Thanks heaps & a gentle fyi to cc: @qpetraroia,  @squillace , @tejhan , @ReinierCC , @davidgamero,  @bosesuneha and @gambtho thank you!
VSIX: 
[vscode-kubernetes-tools-1.3.20-test.vsix.zip](https://github.com/user-attachments/files/19727539/vscode-kubernetes-tools-1.3.20-test.vsix.zip)
> Fix: broken telemetry due to old logic in place.

- src/helm.funcmap.ts
This PR fixes this https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1289 
Thanks and cc: @tejhan ❤️ + @ReinierCC , @bosesuneha , @davidgamero
> Fix wrong sub doc.

- src/components/logs/app/index.html
- src/components/logs/app/main.js
This PR fixes a small UI issue where selected inputs don't visually reset when clicking the reset button. Also some small misalignments were corrected. 
Fixes issue #1521 
.vsix for testing: [vscode-kubernetes-tools-1.3.22-loguifix.vsix.zip](https://github.com/user-attachments/files/19947287/vscode-kubernetes-tools-1.3.22-loguifix.vsix.zip)
> [Fix] Log input updating & alignment fix

- package-lock.json
- package.json
This PR fixes the build which this PR might cause, hence needs engine update with vscode update. https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1513 
thanks heaps, and fyi @tejhan ❤️
> Update vscode engine and package.

- README.md
Removing invalid badge, thanks heaps. @tejhan  as fyi.
> Remove invalid badge.

- src/components/kubectl/kubeconfig.ts
This PR enhances the kubeconfig merging logic to ensure greater user control and consistency. Previously, the merge process would silently skip duplicate entries based on name without properly halting the merge process. This behavior could result in partially merged kubeconfigs and unintended side effects.
Changes 
- **Accurate duplicate detection** for `clusters`, `users`, and `contexts`
- **User confirmation prompt** when a naming conflict is detected, allowing overwrite decisions
- **Flow control enhancements** to prevent partial merges when the user declines to overwrite
These changes ensure that kubeconfigs are merged in a predictable, controlled manner and provides users clearer visibility and decision-making during the process.
Related Issues: …
> Fixing duplicate cluster detection & adding overwrite option

- package-lock.json
- package.json
Hiya, this PR fixes: #1606 
This requires fix for vscode engine as well, therefore the other PR above will be broken. Thanks.
> Fix VSC Engine update and audit.
