vscode-kubernetes-tools/vscode-kubernetes-tools

src/extension.ts
Makes use of the quick picker to fetch logs for pods, removing the requirement that there be a pod in the namespace with a label equivalent to the working directory name. 
Fixes the bug noted in #7.
=> Use quick picker fetching pod logs.

src/extension.ts, src/kubectl.ts
When the pod is running on an image without bash installed, launching terminal would fail. See the bug https://github.com/Azure/vscode-kubernetes-tools/issues/15
=> Check the shell environment on pod to fix the terminal launch failure issue

package.json, src/extension.ts
The old VS Code API for launching a debug session was removed a couple of releases ago, which broke our Kubernetes Debug command.  With this change we invoke the new API and it works again (at least, it works as well as it ever did!).
=> Use the new VS Code debug API

CONTRIBUTING.md, README.md, package.json, src/acs.ts, src/configurefromcluster.ts, src/createcluster.ts, src/extension.ts, test/configurefromcluster.test.ts, test/fakes.ts
We already had a 'Configure from ACS' command which would list ACS clusters in the user's Azure account and download and configure kubectl for a selected cluster.  This adds a choice of 'what cluster type do you want to point kubectl at', with options currently of AKS and ACS.  As with 'create cluster', it is intended that this should be extensible to custom clusters, GKE, EKS, etc. but this will currently be quite clunky - we will work with anyone who wants to implement this support, though, rather than speculatively refactoring now.
Fixes #3.
=> Support configuring the extension from AKS

src/draft.ts, src/extension.ts
Fixes #25.  Note we want to use a terminal rather than the output window because:
1. `draft` uses escape sequences to display a spinner - if we send stdout to the output window then you get a series of lines like `Building Docker image... / Building Docker image... -- Building Docker image... \` which looks silly.  (Using the terminal also gains us colorisation, at least in bash.)
2. `draft up` can take a long time, and using the terminal means we can have the output displayed as draft runs instead of it going dark for ages and then dumping all the output at once.
=> Do not close terminal after draft up completes

README.md
The change log link in the README was lower-cased, but the file name was upper-case.  This resulted in a 404 when clicking the link in the README.
=> Fixed change log link

src/helm.completionProvider.ts, src/helm.documentProvider.ts, src/helm.exec.ts
The Kubernetes extension will tend to activate in most VS Code sessions, e.g. to populate the Kubernetes tree view.  Because of the way the Helm completion provider initialises, this means it will look for charts whenever the user opens a new folder.  At the moment, if there are no charts, the extension displays a "No charts found" error.  As most folders have nothing to do with k8s or Helm, this results in a lot of spurious errors!
This PR suppresses the "No charts found" prompt during completion provider initialisation.  It will still be seen if the user attempts to execute a Helm command in a non-Helm directory.
=> Fix Helm "No charts found" error when opening arbitrary folder

src/azure.ts, src/configurefromcluster.ts, src/createcluster.ts, src/sleep.ts
After creating a cluster, the user can now opt to wait for the cluster to come up, and configure kubectl (and thereby the extension) to point to the new cluster.
Fixes #33, except for the TLS handshake timeout issue which seems more fundamental... Also fixes an issue where if the `create` command failed synchronously (e.g. SSH configuration issues) then this was silently ignored and the extension reported that cluster creation was under way.
=> Option to configure extension with a newly created cluster

package.json, src/explorer.ts, src/extension.ts, src/kubectlUtils.ts, src/kuberesources.ts, test/explorer.test.ts, test/fakes.ts, test/kube-config.json
Add more context menus for kubernetes explorer.
- Add icon for Cluster nodes
- Add `Create Cluster` and `Configure from Cluster` entries in tree navigation bar.
- For cluster node: 
+ Show Cluster Info
+ Delete from kubeconfig
- For namespace:
+ Set to Current Namespace
+ Get
(Namespace is newly added to tree, it lets user to easily switch namespace)
- For Node/Deployment/Pod/Services:
+ Get
+ Delete
See the gif below for preview.
=> Add more context menus for kubernetes explorer

README.md, package.json, src/extension.ts, src/telemetry-helper.ts, src/telemetry.ts
This PR provides limited telemetry on extension usage.  It collects data about which commands are requested, but not about the inputs or results of those commands, nor about the use of other features such as intellisense or the tree view.
=> Command telemetry

src/extension.ts, src/helm.exec.ts, src/helm.ts, src/logger.ts
At the moment, if any file is saved while a non-editor window is active (e.g. if you do a Ctrl+Shift+S while a preview window is showing), we display a 'Nothing saved' message from Helm and steal focus for that message.  This is both misleading and rude.  This PR changes the behaviour as follows:
* The message is displayed only if the Helm preview feature has been used.  (Would be good to do it only if the Helm preview was still up, but that will take more investigating.)
* The message does not steal focus.
* The message now says "Helm preview will not be updated" instead of "Nothing saved."
Fixes https://github.com/Azure/vscode-kubernetes-tools/issues/51.
=> Fix Helm "no active editor, nothing saved" warning

src/explorer.ts, src/kuberesources.ts
Feature https://github.com/Azure/vscode-kubernetes-tools/issues/30 to support Config Maps and Secrets on tree explorer. @kyliel @squillace
=> Support config maps and secrets

README.md, package-lock.json, package.json, src/components/kubectl/proxy.ts, src/extension.ts, src/fs.ts
See below for demo:
Runs `kubectl proxy` in a terminal window created by the extension, and then attempts to open the Kubernetes dashboard in the user's browser. 
Fixes #9
=> Adding support for kubectl dashboard

src/extension.ts, src/shell.ts
This fixes a couple of glitches in the Apply command:
1. If the user had not selected any text, it silently exited.  It now applies the whole content of the active document.
2. If the resource did not exist, it exited with a 'resource not found' error.  This is inconsistent with `kubectl apply` which will create the resource if it doesn't exist.  It now warns that this will create a new resource instead of modifying an existing one.
3. If the resource existed, it displayed a diff of the active document against a JSON representation of the resource.  If the active document was YAML, it was hard to spot the differences.  It now detects the type of the active document, and diffs against the appropriate representation.
Fixes #60.
=> Fixes for Apply command

src/debug/debugProvider.ts, src/debug/debugSession.ts, src/debug/debugUtils.ts, src/debug/javaDebugProvider.ts, src/kubectlUtils.ts
Plan to split the local debug support to several PRs for review.
PR1: Define debug framework and add java debug implementation. (**merged**)
PR2: Add node debug implementation.
**PR3: Add debug (attach) support.**
PR4: Enable the new debug framework via kubernetes commands Debug(Launch) and Debug(Attach)
PR5: Support docker-compose.yml ?
=> Support debug attach to a running java pod

src/extension.ts
When you run Exec or Terminal, the extension uses a label that it applies during Run to locate pods associated with the current application.  However, this causes an unhelpful error if the application was not deployed with the extension.  With this PR, if there are no pods identified for the current application, the extension displays a list of all pods, and the user can exec or open a terminal on any of them.
To simplify the functional change, I converted the original code from callback style to async/await.  Reviewers can see these two commits separately to check the fidelity of the conversion.  It would be nice to more strongly type the pod info after deserialisation (there was a latent bug if the app had more than one pod, which types would have caught), but I propose to defer this …
=> Offer all pods for exec/terminal

README.md, package.json, src/components/git/git.ts, src/extension.ts
It was not clear what the Sync command was doing, and the errors were often opaque.  This PR provides a confirmation message of what the command is about to do (check out a Git commit based on the image version), and provides clearer explanations when it fails.
It goes some way towards fixing #68, but we still need to join it up more clearly with other commands through process and/or documentation.
=> Improved Sync command messages and error handling

src/debug/debugUtils.ts, src/debug/javaDebugProvider.ts
This PR provides a third-way to enable java debug options, and also a workaround for the bug https://github.com/Azure/vscode-kubernetes-tools/issues/83
=> Use JVM environment variables to enable java debug options

src/helm.documentProvider.ts, src/helm.exec.ts
There was an issue where the Helm template preview was attempting to execute a template using a path where one of the segments was doubled, e.g. `c:\test\project\mychart\mychart\templates\foo.yaml`.  This occurred because we took the chart path (e.g. `c:\test\project\mychart`, then took the relative path of the template _relative to the containing directory_ (e.g. relative to `c:\test\project` => `mychart\templates\foo.yaml`), then executed the template using the chart directory and the mismatching relative path.
This PR checks if the chart path is a directory (which it should always be), and if so uses _that_ as the relative-to directory, rather than its containing directory.
It also addresses a possible error if a path name contained spaces.
Fixes #98.
=> Fix duplicate intermediate directory in Helm preview path

README.md, src/components/clusterprovider/clusterproviderserver.ts
We have a request from the business to measure how many users choose different cloud Kubernetes services in the Create Cluster and Configure From Cluster commands.  This PR adds telemetry for that, and updates the documentation to clearly identify this to users so they can opt out if they have concerns.  (I will add it to the changelog when I next cut a release.)
=> Telemetry for which cloud services get used in Create and Configure

package.json
=> Don't show Helm Inspect Values in palette, only in context menu

README.md, debug-on-kubernetes.md, package.json, src/debug/debugSession.ts
Sometimes the debugger cannot be launched successfully, and auto cleanup mechanism will cause the user to have no chance to show the logs of the pod to diagnose what happens.  Add a switch to disable the cleanup policy for failure diagnostics.
=> Add a user setting switch to control whether to auto clean up the created debug deployment

package-lock.json, package.json, src/extension.ts
Add `Copy` menu on Kubernetes Explorer. It will copy the resource id to the system clipboard. These menus are only visible for Kubernetes Resource (cluster/namespace/node/deployment/job/pod/service/configMap/secret).
=> Add Copy command to copy the resource id from tree explorer to clipboard

package-lock.json, package.json
fix issue https://github.com/Azure/vscode-kubernetes-tools/issues/147: some yaml errors during the time user input are not fixed by node-yaml-parser, 0.0.9 fix some of them.
=> update node-yaml-parser version to 0.0.9

src/extension.ts
There is an additional space before `logs`. Currently it will show as:
```
$ kubectl__logs_<pod>
```
=> Remove space in log command

package-lock.json, package.json, src/draft/debugAdapter.ts, src/draft/debugDebug.ts, src/draft/draft.ts, src/draft/draftConfigurationProvider.ts, src/draft/draftRuntime.ts, src/extension.ts, test/draft.test.ts
This PR is a work in progress to add native VS Code experience to run and debug apps deployed with Draft.
It is still rough around the edges and there's lots of things to add and review:
This is a first attempt at integrating with the extension - please provide all types of feedback on debug sessions and how the debugger integrates with the extension.
=> [WIP] Draft debug adapter

package-lock.json, package.json
Exploring an option to prevent `gulp tslint` crashing in the CI environment.
=> Force 'natives' module version to fix gulp tslint crash

README.md, package-lock.json, package.json, src/binutil.ts, src/components/installer/installer.ts, src/components/kubectl/dashboard.ts, src/components/kubectl/port-forward.ts, src/draft/draft.ts, src/draft/draftRuntime.ts, src/extension.ts, src/helm.exec.ts, src/kubectl.ts, src/shell.ts, test/draft.test.ts, test/kubectl.test.ts
This adds an option to the 'kubectl/helm/draft not found' error to install the extension's dependencies -- currently limited to `kubectl`, Helm and Draft.  (We'd like to do Docker and Azure CLI too, but that was a bit much for this PR.)
The experience is that if we detect a missing command line tool (via background e.g. populating the tree view or a command e.g. Helm Create), we pop an alert which now has the addition button "Install dependencies."  If the user clicks this button then we install kubectl, Helm and Draft into a `.vs-kubernetes/tools` directory under their home directory, and set VS Code config settings to point to these private copies.  We do **not** add the binaries to the system path, so if the user tries to run `kubectl` or `helm` at a terminal they will still get 'not …
=> Automatically install missing kubectl, Helm and Draft

src/kubectlUtils.ts
Kubernetes services are not required to have selectors, for example if the service is implemented by an external endpoint.  Clicking a service without a selector in the tree view previously caused an error "Cannot read property 'matchLabels' of undefined".  This fixes that error.
Fixes #190.
=> Fixed error when selecting service without selector in tree

src/extension.ts, src/helm.exec.ts
Several commands which need a workspace (open folder) fail silently when the user doesn't have a folder open.  This PR provides fallback or error reporting behaviour for this scenarios.
Fixes #194.
=> Fix silent failures when there is no workspace

CONTRIBUTING.md, README.md
It's not obvious that you need to install the RedHat YAML extension before running this extension from source (i.e. debugging it in the Extension Development Host).  This PR adds some documentation around that.
Fixes #153.  Well, sort of.
=> Document preequisities for running from source

src/components/clusterprovider/azure/azure.ts
AKS has added a couple of Canada regions to the preview.  We need to offer these in the Create Cluster region drop-down.
=> Add new regions to create AKS cluster wizard

src/extension.ts
Consider the following scenario:
1. The user selects a resource in the tree view (or uses the `Load` command).
2. The extension creates an untitled document containing the resource JSON.
3. The user leaves the document open.
4. Later, the user again selects the same resource (or uses the `Load` command to load it again).
At the moment, this has a bug where the second time, the resource JSON is appended to the existing document.  This PR loads each copy of the resource into a new document.  Documents are named e.g. `deployment-foo.json`, `deployment-foo.1.json`, `deployment-foo.2.json`, etc.
A nice enhancement to this would be to compare the current JSON against the content of the existing document, and simply re-show that document if the resource had not changed.  This would avoid …
=> Fix copy of a resource being appended when resource re-selected

README.md, package.json, src/components/clusterprovider/azure/azure.ts, src/components/kubectl/dashboard.ts, src/components/kubectl/port-forward.ts, src/debug/debugSession.ts, src/draft/draft.ts, src/draft/draftRuntime.ts, src/explorer.ts, src/extension.ts, src/host.ts, src/kubectl.ts, src/shell.ts
We've had a few people who have multiple kubeconfig files and want to be able to swap between them.  This PR adds a setting (which can be at user or workspace level) to control which kubeconfig file is used.
Considerations for reviewers:
* Is a setting discoverable enough, or should users be able to swap using a hotkey?  Or should we even display multiple kubeconfigs in the tree view and allow users to switch between them?
* Are there any paths I have missed that spawn kubectl or anything else that uses kubeconfig?  I _think_ I have them all, but we have sprouted quite a few places that go round the back of the abstractions.  Please check areas that you know to be sure I haven't messed them up (e.g. @radu-matei's Draft debug stuff).
* In order to minimise the risk above, I've tried to …
=> Support alternate kubeconfigs

README.md, package.json, src/extension.ts
Resolves #212. 
- Uses yaml output by for viewing k8s manifests.
- Adds a configuration option for viewing k8s manifests in json.
=> Adding configurable output formats for load command

src/components/clusterprovider/azure/azure.ts, src/components/clusterprovider/azure/azureclusterprovider.ts, src/components/git/git.ts, src/components/installer/installer.ts, src/extension.ts, src/wizard.ts
The `Errorable<T>` interface (which represents the result of an operation that might fail with an error) is currently not type-safe - the `result` and `error` properties are both always present, whether the result was success or failure.  This makes it hard to add strict null checks as it is not always possible to give meaningful values for `result`.  It is safer to define `Errorable<T>` as a union of success and failure cases: this makes TypeScript check for safe usage, and avoids the need to pass null or undefined results in the error case.  This removes an obstacle to strict null checking in a future PR.
=> Making Errorable<T> more type safe

src/components/installer/installer.ts, src/debug/debugSession.ts, src/extension.ts
The Terminal, Exec and Logs commands previously always operated only on the first container of a multi-container pod.  This PR prompts for the container if the pod contains multiple containers.  Note that Debug (Attach) and Sync already handled multiple containers (the former on a different code path) - I've rationalised the UI but have not consolidated the Debug (Attach) selection code.
Fixes #203, although the original post there asked for containers to be displayed in the tree view; we can add that too if people feel strongly about it.
=> Support container-level operations on multi-container pods

package.json, src/extension.ts, src/kuberesources.virtualfs.ts
When someone does a Load command, or clicks on a resource in the tree to load its JSON/YAML, we want three things:
* The user should be able to close the JSON/YAML and not be bugged with a save prompt (or be left with a temp file in their project)
* The user should be able to save the JSON/YAML
* The user should be able to edit the JSON/YAML and be prompted to save
Loading filesystem documents violated the first bullet, as we had to poke the JSON/YAML into a document which made it dirty and ask to be saved.  Using a TextDocumentContentProvider violated the other two as you couldn't save or edit the document.
This attempt abuses VS Code 1.23 file system providers to try to solve the problem.  The Load command now loads from a URI scheme backed by a FileSystemProvider instead of a …
=> Yet another run at the "display Kubernetes resource manifests from cluster" problem

package.json
When a Helm template YAML file is not directly in `.../templates`, but instead in a subdirectory (e.g. `.../templates/my-template`, it is currently identified as the YAML filetype rather than the helm-template file type.  This PR treats `.yaml` and `.tpl` files _anywhere_ under the `templates` directory as file type helm-template.
Fixes #225.
=> Helm templates can live in subdirectories under /templates

src/components/clusterprovider/azure/azure.ts, src/components/clusterprovider/azure/azureclusterprovider.ts, src/components/git/git.ts, src/components/installer/installer.ts, src/components/kubectl/dashboard.ts, src/components/kubectl/port-forward.ts, src/configMap.ts, src/debug/debugSession.ts, src/errorable.ts, src/explorer.ts, src/extension.ts, src/kubectl.ts, src/kubectlUtils.ts, src/kuberesources.objectmodel.ts, src/shell.ts, src/wizard.ts
This PR defines some interfaces for Kubernetes resources and collections, so that when we work with them (e.g. after loading them from JSON) we can work with them in a safer way.  It's motivated by having to hold 'what is this `any` representing... is it a Foo or some internal type containing interesting data from a Foo... what fields does it actually have... etc.' in my head.  The main additions are the resource interfaces themselves (which contain only the fields we're interested in, but that's okay, they don't need to be comprehensive) and the `kubectl.asJson` method which encapsulates the JSON parsing and type assertion (and should be used in preference to `invokeAsync` when we are requesting JSON for materialisation as an object).
These changes don't prevent maintainers from using …
=> Kubernetes resource object types

src/components/clusterprovider/azure/azure.ts, src/components/clusterprovider/azure/azureclusterprovider.ts
This is a tale of shame and ignorance.
The existing Azure Create Cluster code assumes the user has already generated SSH keys.  If not, the Azure CLI fails with an error telling you to pass `--generate-ssh-keys`.  I've been improving the checks around this but they still seem to be unreliable, but I didn't want to pass `--generate-ssh-keys` because I didn't want to clobber any existing SSH keys or to create new ones that the user didn't know about.
It turns out, as the `az aks create` documentation _clearly states, Ivan, very clearly_, that the generate option does NOT clobber existing keys, does not even generate new keys if existing ones already, er, exist, and even emits a helpful message WHICH THE EXTENSION WOULD ALREADY DISPLAY warning the user if new keys were created and where to …
=> When creating cluster, generate SSH keys if missing

package-lock.json, package.json
We have a 'known vulnerable dependency' flag from GitHub for growl 1.9.x.  I don't think the vulnerability is an issue for us, but we want to make it go away.
The naughty version is brought in by an old version of mocha, so I upgraded that as well (to a version consistent with the vscode package).
=> Update growl to 1.10.x, whose security vulns remain unknown so far

src/components/kubectl/port-forward.ts, src/extension.ts, src/kuberesources.objectmodel.ts
The Kubernetes API docs allow you to have a spec without a `metadata.namespace` element, and say this is equivalent to the `default` namespace (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#objectmeta-v1-meta).  We had done some improvements around supporting namespaces which incorrectly assumed that the namespace would always be present; this need not be the case.
Fixes #248.
=> Fix diff and apply error when metadata.namespace not present

src/components/kubectl/port-forward.ts, src/extension.ts
This PR fixes a couple of issues with the Apply command:
* You can't Apply a multi-resource YAML.  This is because Apply wants to show you a diff against the existing cluster configuration first, and we don't yet handle diffing multiple objects.  The fix for this is to cheat: we now put up a warning saying "hey we can't show you what's going to change but would you like to go ahead and apply it anyway?"
* You can't Apply changes made to a resource loaded via Load.  There is a workaround, to save the YAML, close it, open it from the file system and make the changes and apply them; but this PR enables the much simpler workflow of "Load > edit text > Apply".
This PR involved some slightly fiddly and hard to test changes to some pretty old code, so it might be best to consider it WIP for now …
=> Fix limitations on Apply command

src/helm.exec.ts
A user (stop looking shifty, @chzbrgr71, we see you) reported that the accursed and thrice-accursed 'chart not found' message was still popping up and making his kittens sad.  This also made me sad because I had fixed the damn thing _at least_ once already and I did not want to spend my twilight years suppressing the same message in ever more creative ways.  Hours of pinpoint debugging revealed that the error occurred under the wild and extreme conditions of having a YAML file open at extension startup.  This took a different code path from the previous fix, on which I failed to check the vital "stop bugging Brian with annoying messages" flag.  This PR checks the flag, and occasionally mutters darkly to itself about mysterious enemies.
=> Fixed invalid 'chart not found' message if YAML file open on startup

package.json, src/explorer.ts, src/extension.ts, src/kubectlUtils.ts
ACS and AKS tend to provide fairly user-hostile cluster/context names.  Contexts can be renamed using `kubectl config rename-context`, but clusters can't.  So it is preferable to display context names in the tree view so that users can replace them with beautified ones.
I also took the opportunity to rename the tree to **Clusters**, because the Kubernetes label is already prepended by virtue of being on the new Activity Bar tab.
Fixes #178.
=> Display context name instead of cluster name in tree view

src/components/kubectl/dashboard.ts, src/components/kubectl/port-forward.ts, src/extension.ts
Fixes #185 
Allows users to enter multiple port bindings:
ex: 8888:80 8889:81 or 80 81 (for random assigned ports)
=> Port forward with multiple ports

src/explorer.ts, src/kubectl.ts, src/kubectlUtils.ts
@itowlson this fixes the issue with the pod status in node explorer view. Wanted to open an PR for feedback to see if we should move to `JSON` based parsing of status as compared to column based parsing. Also wanted to get some clarification on use of [`getPods`](https://github.com/Azure/vscode-kubernetes-tools/blob/master/src/explorer.ts#L258) vs [`kubectl.asLines`](https://github.com/Azure/vscode-kubernetes-tools/blob/master/src/explorer.ts#L181) to get pod information as to which is the preferred method. Happy to refactor `getPods` to reflect pod status.
=> Fix for Pod status in Node Explorer View #272

src/explorer.ts
While refactoring for #277 missed the where the `matchLabels` are empty (as current namespace is selected) for  `Services` -> `<Service-Name>` and hence pods under an service were not showing up and the extension threw an error. This PR fixes that. Sorry about breaking this functionality.
=> Fixing pod listing for services in explorer view

package.json, src/explorer.ts, src/extension.ts, src/helm.exec.ts, src/kuberesources.virtualfs.ts
This adds a new top-level 'Helm Releases' node to clusters in the tree view.  At the moment there's not much you can do with this - viewing the node displays the `helm get` output as a text file, and that's it.
This is currently work in progress - it needs to be tested with large numbers of releases, and I would like feedback on whether to present the returned file as YAML (which it isn't, not really, but it colourises okay if you pretend it is) or as plain text.  Other feedback / suggestions welcome (but may be deferred to subsequent enhancements).
Fixes #245.
=> Show Helm releases in cluster tree view

src/explorer.ts, src/helm.exec.ts
If there was an error listing Helm releases, the tree view previous just said "Helm list error".  This PR adds a tooltip with the error message from the Helm CLI.
=> Provide additional diagnostics when unable to display Helm release list

src/components/kubectl/logs.ts, src/extension.ts
Fixes #273.
Logs will be invoked in a new terminal when invoked from the command palette with the 'Follow Logs' command.
Additionally, fixes a TODO I had noticed in which Terminal invocation would only work for Pods in the current namespace.
=> Logs invoked in new terminal

src/components/kubectl/port-forward.ts, src/debug/debugProvider.ts, src/debug/debugSession.ts, src/debug/debugUtils.ts, src/debug/javaDebugProvider.ts, src/extension.ts, src/kubectlUtils.ts
When we added the feature to expand the pods under a node, we deferred dealing with pods that were outside the active namespace.  An earlier PR made it so they loaded correctly but other commands still didn't work.  This PR fixes the following commands:
* Get
* Delete
* Debug Attach
* Port Forward
* Describe
The remaining commands (Terminal, Show Logs, Follow Logs) are addressed in #279.
=> Fix remaining tree commands that didn't work on namespaced pods

src/components/download/download.ts, src/components/installer/installer.ts, src/shell.ts
The Azure CLI and kubectl both use the HOME environment variable, falling back on USERPROFILE only if HOME is not defined.  We had a bug where, when we spawned them, if we were on Windows, we always set HOME to the value of USERPROFILE.  So if a user had a custom HOME, spawning would break.
Fixes #301.
=> If HOME is defined on Windows, then use that rather than USERPROFILE

src/explorer.ts
A follow-up comment on #291 identified that the Helm Releases tree node provided a Get command which, when invoked, tried to retrieve Helm releases using `kubectl`.  This occurred because the Helm Releases node was implemented using the Kubernetes resource folder infrastructure and inherited the common behaviour of that infrastructure.  This PR removes the kludge; the folder is now treated as a non-resource folder, and does not display a Get command.
Thanks @mozesmagyar for reporting the issue!
=> Do not show spurious Get command on Helm Releases tree folder

src/components/clusterprovider/azure/azureclusterprovider.ts, src/components/clusterprovider/clusterproviderregistry.ts, src/components/clusterprovider/clusterproviderserver.ts, src/components/clusterprovider/minikube/minikubeclusterprovider.ts, src/components/download/download.ts, src/explainer.ts
Some of our dependencies take a very long time to load.  This PR defers loading these dependencies until they are needed`*`.
Fixes #307.
~~`*` _conditions apply_... specifically, the `restify` dependency is not yet fully deferred, as we currently need to start HTTP servers during activation in order to parcel out ports to the various providers.  I'll keep noodling away on this and push an update if I can see a reliable way to do this.~~  The `restify` dependency is now _even more deferred_.
=> Improve startup speed

src/components/kubectl/compatibility.ts, src/kubectl.ts, src/shell.ts
This PR addresses two versioning issues with `kubectl`:
1. Terminals could use a different version of `kubectl` from "behind-the-scenes" calls, if the user had set a location for `kubectl` in their VS Code configuration.  This occurred because "behind-the-scenes" would directly invoke the program at the configured location, whereas terminals would append the configured location to the path (so that the user could issue follow-up commands without having to type out the configured path) -- so if `'kubectl` was _also_ on the path then the path version would take precedence.  This meant the kubectl terminal was consistent with a system terminal, but made it hard to diagnose/reproduce the behaviour of "behind-the-scenes" commands.  Terminals now _prepend_ the configured location to the path, …
=> Fix kubectl versioning woes

src/extension.ts
As part of showing or following logs, we need to check whether the pod contains multiple containers (so we can prompt for which container's logs the user is interested in).  We do this using a `get pod` query with a JSONPath that lists the container names and images in the pod.
Unfortunately, it turns out that JSONPath expressions are portable across Windows and Linux, but _not_ to Mac - they need a different quoting style on Mac.  Linux also accepts the Mac style, so this PR modifies the JSONPath to use Windows-friendly quoting on Windows and Mac-friendly quoting on both Unices.  So it now appears to work okay on all three OSes.
Fixes #315.
=> Fix JSONPath parsing error when checking containers in a pod

package-lock.json, package.json, src/helm.repoExplorer.ts
If a Helm repo URL contained a path, e.g. `https://azure.github.io/brigade`, we were blatting that path with `index.yaml` instead of appending `index.yaml` to the end of the path.  This prevented us from listing the charts in the repo.  This PR fixes that issue, and also adds hover detail for errors should there be any more lurking in there.  WHICH THERE ARE NOT.
=> Fix error listing charts in Helm repo if repo URL contained a path

package-lock.json, package.json
We have an indirect dependency on something called mixin-deep (through about five levels of weirdly named stuff, so no idea why or how).  This has had a vulnerability report raised against it.  So we need to update it to a new version.  Whee.
=> Trade up a version of mixin-deep with a known vulnerability for one which is excitingly unknown

src/components/clusterprovider/minikube/minikube.ts, src/components/clusterprovider/minikube/minikubeclusterprovider.ts, src/components/installer/installer.ts, src/extension.ts, src/shell.ts
This adds Minikube to the 'Install dependencies' prompt, and adds missing dependency detection to the Minikube 'create cluster' wizard.  As dependencies are installed in a private location rather than on the path, this also requires some hardening of the Minikube detection and launch logic which brings it more in line with kubectl and Draft.
Fixes #300.
=> Install Minikube if not present

package.json
Make helm template extension features work on `*.yml` files
=> Enable extension features for *.yml files

src/components/clusterprovider/azure/azure.ts
Apparently, we forgot to add japan when we released aks there - oops.
=> Adds japaneast and southeastasia azure regions

package.json, src/extension.ts, src/helm.documentProvider.ts, src/helm.exec.ts, src/helm.repoExplorer.ts, src/helm.ts
This provides a context menu for charts and chart versions in the new Helm repo explorer tree view.  Commands implemented so far:
* `Install`
* `Fetch`
* `Inspect Chart`
* `Inspect Values`
* `Show Dependencies`
~~The original issue also asks for `Dependencies` but there's a question mark over how to implement that - will push an update and remove the WIP tag when that's resolved (or parked).~~
Fixes #323.
=> Helm repo explorer context menu

README.md, package.json, src/components/clusterprovider/azure/azure.ts, src/components/config/config.ts, src/components/installer/installer.ts, src/extension.ts, src/shell.ts
Some users have multiple Kubernetes environments which they keep in separate kubeconfig files.  For working with relatively static kubeconfigs (e.g. single alternate kubeconfig, kubeconfig per project, etc.) we have the `vs-kubernetes.kubeconfig` setting which can be applied at global or workspace level.  But if the user wants to be able to swap more dynamically then they have to keep changing that setting and that is a bit niggly.
This PR adds a `Set Kubeconfig` command.  This command displays a list of 'known kubeconfigs' from which the user can choose.  The user can also choose to add a new known kubeconfig, which immediately becomes selected and is added to the list of known kubeconfigs.
In addition, the command supports passing a kubeconfig file path as an argument.  This means that …
=> Support rapid switching between multiple kubeconfigs

README.md, package-lock.json, package.json, src/explorer.ts, src/extension.ts, src/fs.ts, src/helm.authoring.ts, src/helm.exec.ts, src/helm.symbolProvider.ts, src/host.ts, src/kuberesources.virtualfs.ts
This PR provides support for authoring Helm templates based on existing resources.  The intended workflow is as follows:
* Open a resource in the cluster explorer tree view and invoke the `Helm: Convert to Template` command.  (You can also right-click the resource and choose `Convert to Template` from the context menu.
* You are prompted for a template name (and, if necessary, a chart to add it to).
* A template is created in the chart's `templates` directory.  Initially, we only 'templatise' the `metadata.name` and `metadata.labels.chart` fields.
* You can now move the cursor to any value in the template and invoke the `Helm: Convert to Template Parameter` command.
* The extension replaces the value with a template expression (`{{ .Values.widget.snoofles }}`) and creates a corresponding …
=> Create Helm templates from resource manifests

src/explorer.ts, src/kuberesources.ts
First cut of an update for storage-related resource types - it just adds them to the tree view with the same set of verbs as other resources.  Should there be other/different operations, and are any other resource types required?
Fixes #338.
=> Add persistent volumes, PV claims and storage classes to tree view

package.json
If you leave a resource open (from the cluster view) and then close and reopen VS Code, it restarts with the resource tab open, wabbles for a bit and then closes the resource tab.  This occurs because VS Code tries to reopen documents, but when it tries to load the content of the 'resource' document, it can't find anything to handle the `k8smsx` URI scheme.
This PR specifies to activate the extension if Code needs the `k8smsx` URI scheme, thus allowing Code to load the tab content.
(It might arguably be better for Code not to try to reopen the tab at all but I don't think we have that option.)
=> Activate if the extension is needed for re-opening live resources

src/components/lint/linter.impl.ts, src/components/lint/linter.utils.ts, src/components/lint/linters.ts, src/components/lint/resourcelimits.ts, src/extension.ts, src/yaml-support/jsonalike-symbol-provider.ts
We're finding that a common mistake that people make with Kubernetes is to deploy workloads with no limits on memory or CPU consumption.  This PR displays green wigglies and a 'Problem' indicator in VS Code when the user opens a YAML file for a pod or deployment which does not limit memory and CPU in this way.
This is an initial posting for review and feedback - I don't think things like wording are final.  We should probably sanity check things like the CPU limit as well...
Fixes #344.
=> Warn if a pod or deployment does not specify CPU or memory limits

src/helm.exec.ts
Somehow I did this and then forgot to send the PR!
Fixes #363.
=> Fix for Helm Insert Dependency command not working on Windows

src/components/json/jsonhierarchicalsymbolprovider.ts, src/components/lint/linter.impl.ts, src/components/lint/resourcelimits.ts
There was an issue with multi-document YAML files where the linter silently exited instead of providing warnings on pod or deployment resources within the YAML.  This was due to using the `safeLoad` method instead of `safeLoadAll` (`safeLoad` throws on multi-document sources).  With this PR, linting will work on both single and multiple resource YAML files.
As part of testing this fix, I found that JSON linting wasn't working correctly even for single documents (apparently my "JSON-a-like" YAML symbol provider was not as JSON-like as I thought, BUT BETTER SO MUCH BETTER), and fixed that too.
Fixes #359.
=> Fix resource linting in JSON and multi-document YAML files

src/shell.ts
The implementation of kubectl prefers %HOMEDRIVE%%HOMEPATH% over %USERPROFILE% to determine the user's home directory. While the first alternative may point to a directory located on a network drive, the second alternative always points to a directory on a local drive. The VS code extension should follow the lookup behavior of kubectl in order to maintain a consistent user experience (when ran from a shell, kubectl picks up a different config file).
=> Prefer %HOMEDRIVE%%HOMEPATH% over %USERPROFILE%

README.md, src/extension.ts, src/telemetry-helper.ts
Adds information about whether a cluster is Azure, Minikube or 'other' to command telemetry.
~~**IMPORTANT NOTE TO SELF:** Do not merge until we have updated the disclosure statement in the readme!~~ Disclosure updated.
=> Cluster type telemetry

README.md
The README is in a bit of a muddled state, much of it dating back to the handover from its parents.  We want to lead on information that will help potential users to evaluate whether it is going to be worth their while.
With this change the README leads on the target audience and the feature list, and refines the prerequisites into a 'getting started' section (moving the "except if the moon is in Pisces" stuff out to footnotes).
=> Rewrite and reorganise README to help readers evaluate extension

src/helm.resources.ts
The Helm intellisense tries to load schemata from the `.kube/schema` directory.  If this does not exist, or if it is empty, then the resulting errors are not handled correctly, and activation can fail.
Fixes #422.
=> Fix errors and crashes loading schemata from disk for Helm intellisense

src/helm.exec.ts
In the olden days, if you right-clicked `requirements.yaml` in the file explorer and chose Update Dependencies, it would ignore the context and prompt you for which chart to update.  This was bad.  With the coming of #426, this was improved by making it misinterpret the context and silently error out of the command.  This was worse.
This PR makes it update the dependencies of the chart containing the clicked `requirements.yaml`, without prompting or crashing or any of that fun stuff.  This... _glances to side at PM, blinks rapidly to reader in Morse code_... this is better.
=> Fix for running Helm Update Dependencies from the file explorer

README.md
Somehow we've managed to go without an installation link in the README - I fixed that.
=> Add installation link

CHANGELOG.md
I forgot to update the 0.1.15 changelog thanks list to reflect late-breaking contributions to 0.1.15 by @shreyu86 and @dgkanatsios.  This PR restores the due credit.
=> Fix contributors who were not properly credited on the 0.1.15 release

src/components/clusterprovider/minikube/minikube.ts, src/draft/draft.ts
is there a way to modify test to have a bin path with space?
please note that i'm unable to launch the test suite localy. Seems that i have a compile error (not related to this PR)
`src/components/kubectl/port-forward.ts(237,13): error TS2322: Type '{ succeeded: boolean; pod: string; namespace: string; fromOpenDocument: true; }' is not assignable to type 'PortForwardFindPodsResult'.`
=> Support space in path to minikube bin #441

src/kubectl.ts
Because that way madness lies.
We had a situation where if a `kubectl` command failed, we would call `kubectl version` to see if the failure might be down to a client-server mismatch.  But if `kubectl` itself errored in response to `kubectl version -o json` (for example, if `kubectl-path` pointed to a binary other than the true kubectl), then this counted as a failure that would trigger the client-server compatibility check.
As we run `kubectl config` on startup to find out what context we're in, this resulted in the extension going into an infinite loop on activation if confronted with an uncooperative kubectl.
We fix this by recording that the compatibility check has been initiated _before_ calling `kubectl version`, and not repeating it if the check has already been initiated.
Fixes …
=> If we can't check compatibility, we shouldn't check if that's a compatibility issue

snippets/replicationcontroller.yaml
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#container-v1-core
According to API(v1.9, 1.10, 1.11, 1.12, 1.13) Container's port field should be named "port**s**"
=> Fix typo in ReplicationController snippet

package-lock.json, package.json, src/components/installer/installer.ts, src/draft/draftConfigurationProvider.ts, src/fs.ts, src/kuberesources.linkprovider.ts, src/kuberesources.virtualfs.ts
The latest version of VS Code runs on Node 10.  This updates our Node type declarations to v10 to better check compatibility (though it looks like we were okay).
It looks like the CI was already using Node 10, so I don't think we need to update anything there.
Creating this PR now to allow CI to noodle on it.  @bnookala would you mind taking a look to see if you think I've overlooked anything please?  But let's not merge until the latest VS Code has been out there a little longer.  Thanks!
=> Update to latest VS Code engine and Node 10 types

package.json, src/explorer.ts
VS Code now supports menu contribution `when` clauses using regexes.  This means we can give each k8s resource node a distinctive context (e.g. `vsKubernetes.resource.deployment`), but apply the common commands to them via a pattern.  This reduces duplication (and errors, and inconsistencies!) compared to having to apply commands to every resource type individually.
=> Consolidate explorer right-click commands using context regexes

src/components/wizard/wizard.ts
In the course of reporting/resolving the "spurious 'null' at the top of Web views" issue (https://github.com/Microsoft/vscode/issues/68953), we've been advised to use full HTML documents for Webviews rather than fragments.  (This doesn't work around the spurious text - they've fixed that upstream - but it's just a sensible idea anyway.)
=> Use full HTML documents for Web views

src/kubectlUtils.ts
If two contexts point to the same cluster, deleting both would fail because the first would remove the underlying cluster and user from the kubeconfig file, and the second would then complain because trying to delete the cluster failed.  Because one of these prior deletions can fail on 'not in kubeconfig', we should press on to try to delete the context even if cluster or user deletion fails.
A smart fix would check if the reason for failure was that the cluster (or user) didn't exist.  This is not a smart fix.
Fixes #482.
=> When deleting context, press on even if cluster or user didn't delete

package-lock.json, package.json, src/extension.ts, src/kubectlUtils.ts, src/utils/naming.ts
This adds the functionality to run a CronJob immediately (that is, to create a 'normal' job from a CronJob).
Fixes #469.
~~(ETA: in order to avoid having to duplicate menu contributions for a new `vsKubernetes.resource.cronjob` tree node context, I switched over the menu contributions in `package.json` to use regular expressions on the context when clause.  This is orthogonal to the functional changes.  I can unpick it into a separate PR if it makes this one hard to read.)~~  This PR depends on #473 which separates out the refactoring of the explorer command contributions.  Once #473 is merged I can rebase this and it will reduce the noise.
=> Run CronJob immediately

README.md, package-lock.json, package.json, src/components/config/config.ts, src/components/download/download.ts, src/components/installer/installationlayout.ts, src/components/installer/installer.ts, src/components/kubectl/autoversion.ts, src/extension.ts, src/fs.ts, src/host.ts, src/kubectl.ts, src/kubectlUtils.ts, src/utils/filebacked.ts, src/utils/mkdirp.ts
Some customers - specifically the critical customer demographic known as _me_ - have clusters from multiple Kubernetes versions.  It is not always possible to find a version of `kubectl` that works with all clusters, because `kubectl` is only guaranteed to work up to 2 API versions away.  For example, if I use my 1.9 kubectl then I can't see pods in the 1.7 cluster, but if I use my 1.7 kubectl then I can't deploy CRDs into the 1.9 cluster.
This PR adds an _opt-in_ option by which, instead of users specifying a `kubectl` binary, we inspect the cluster, download the matching `kubectl` binary and use that.  This is opt-in because I'm worried about performance impact; later we could change it to opt-out so as to make it more transparent.  Cluster versions and kubectl binaries are cached and …
=> Kubectl per cluster version

package.json, src/extension.ts
A cluster provider normally activates in response to one of the wizard commands.  If the _core_ Kubernetes extension was not already active at that point - that is, it is the wizard command that's activating the core extension - then the core extension activates and sometimes the wizard command would start to run _before_ the cluster provider could activate and add its entry to the cluster types list.  This would require the user to cancel and restart the wizard, so that it would include the now-registered cluster type.
This PR works around this by forcing VS Code to await the execution of a dummy, no-op command before starting the wizard.  This seems to give extension-extensions the chance to complete their activation before the first page of the wizard is displayed and the cluster …
=> Fix for contributed cluster types not appearing first time if extension activated by wizard command

package.json
Creating a preview version so that users wanting to try out the new API don't need to build the extension themselves.  This will be distributed only as a VSIX via a GitHub release page; it will not go to the marketplace.
=> Bump version for API preview consumers

docs/extending/kubectl.md, package.json, src/api/contract/kubectl/v1.ts, src/api/implementation/kubectl/v1.ts
Port forwarding is a bit fiddly, and is not readily supported by the simple `invokeCommand` abstraction which waits for command completion.  So it would be useful to facilitate it in the API.  (More generally, we should consider adding an 'invoke background' facility on top of which port forwarding could be built.)
=> Add port forwarding to the API

docs/extending/helm.md, docs/extending/kubectl.md, src/api/contract/helm/v1.ts, src/api/implementation/apibroker.ts, src/api/implementation/helm/v1.ts, src/api/implementation/helm/versions.ts
The primary purpose is to support extensions that want to install tools via Helm charts.  But it may as well be a general-purpose invocation API.
=> Added a basic Helm API

docs/extending/README.md, docs/extending/cloudexplorer.md, package.json, src/api/contract/cloudexplorer/v1.ts, src/api/implementation/apibroker.ts, src/api/implementation/cloudexplorer/v1.ts, src/api/implementation/cloudexplorer/versions.ts, src/components/cloudexplorer/cloudexplorer.extension.ts, src/components/cloudexplorer/cloudexplorer.ts, src/components/kubectl/kubeconfig.ts, src/extension.ts, src/fs.ts, src/utils/providerresult.ts
This provides a host for users to browse cloud resources.  It's pretty generic, though with specific support for adding kubeconfig entries when the resource being viewed is a Kubernetes cluster.
No clouds are built in; instead, the user can install cloud providers from the marketplace and they can register themselves to display content in the tree.
=> Cloud Explorer

src/components/platform/browser.ts
I hit a problem where external browser windows weren't opening.  Looking at the docs, it seems like if the `openExternal` API is present then it's failing because we're passing it a string when it wants a `vscode.Uri`.  This PR fixes that.
=> vscode.env.openExternal takes a Uri

package.json
The UI customisation API opens up the possibility for evildoers (not _you_, dear reader; lollards and schismatics, but never you) to modify the `treeItem.contextValue` of explorer nodes.  While we can't (short of wrapping the entire TreeItem API) stop them doing this, we can encourage them to append to the context value instead of replacing it entirely.
Our current menu contribution entries don't quite allow for this though, as they either do an exact match or do a regex match with start and finish metacharacters.  This PR modifies it so commands always pattern-match, and allow the pattern to appear anywhere in the string.  So commands should continue to appear as long as we have _civilised_ evildoers.
=> Match appended view item contexts for commands

docs/extending/cloudexplorer.md, package.json, src/components/cloudexplorer/cloudexplorer.ts, src/extension.ts
Fixes #524.
Added a command which users can get to by:
* Clicking the 'no clouds registered' message
* Dropping down the `...` thingy on the Cloud Explorer title bar
* Command palette as usual
This will launch a search for the keyword `kubernetes-extension-cloud-provider` which is specified in the documentation for writing a cloud provider.
=> Explorer link to cloud providers on marketplace

docs/extending/clusterexplorernodes.md, package.json, src/api/contract/cluster-explorer/v1.ts, src/api/implementation/cluster-explorer/v1.ts, src/explorer.ts
Per preview feedback, adds APIs to the ClusterExplorerV1 interface/namespace for defining resource folders and grouping folders without implementing the whole thing yourself.
Samples:
Adding Network Policies to the Network folder:
```
clusterExplorer.api.registerNodeContributor(
clusterExplorer.api.nodeSources.resourceFolder("Network Policy", "Network Policies", "NetworkPolicy", "netpol").at("Network")
);
```
Adding a Security folder to the context node:
```
clusterExplorer.api.registerNodeContributor(
clusterExplorer.api.nodeSources.groupingFolder("Security", undefined,
clusterExplorer.api.nodeSources.resourceFolder("Role", "Roles", "Role", "roles"),
clusterExplorer.api.nodeSources.resourceFolder("Role Binding", "Role Bindings", "RoleBinding", "rolebindings"), …
```
=> Cluster explorer convenience API

docs/extending/kubectl.md, package.json, src/api/contract/kubectl/v1.ts, src/api/implementation/apibroker.ts, src/api/implementation/kubectl/v1.ts, src/api/implementation/kubectl/versions.ts, src/components/kubectl/port-forward-ui.ts, src/extension.ts
Currently only for port forwards done via the API.  But eventually we should consolidate all behind-the-scenes port forwarding.
~~TODO: docs.~~ <-- Done
=> Display active port forwards in the status bar

src/kubectl.ts
Fixes #565.
The underlying issue is that someone forgot that `kubectl` table output is meant to be parseable by tools such as `awk`, and that multi-word column headers should therefore be hyphenated instead of spaced.  This person added a pod column called `NOMINATED NODE`.  Because we parse based on space-separation, we interpreted this as two columns, `NOMINATED` and `NODE`.  And the spurious `NODE` column duplicated and overwrite the real `NODE` column which we needed to relate pods to nodes.
Fortunately it seems that we can - for now at least - rely on at least three spaces between columns, per the TabWriter implementation and the settings in the k8s `tabwriter.go` file.  So there is a simple fix to set the column separator regex to at least two spaces.  It would be good to get this …
=> Fix node pods not displayed with kubectl 1.12+

src/components/kubectl/kubeconfig.ts
When you merge a kubeconfig from Cloud Explorer, it checks if an entry name already exists and if so skips that entry.  The message currently says `[object Object] already exists - skipping`.  This displays the name instead.
Fixes #540.
=> Fix [object Object] if kubeconfig merging from Cloud Explorer exists

package-lock.json, package.json
Because it pulls in a very old version of Application Insights, and AI has been implicated in an issue with HTTP requests from other extensions; so if we are going to need support with that then we want to be on the latest version.
=> Upgrade telemetry package

language-configuration.json
Removed `{{-` `autoClosingPairs`
Closes #571
=> Fix annoying double autocomplete bug

src/components/clusterprovider/minikube/minikube.ts
This fixes an error when querying the status of minikube by choosing a `--format` string appropriate for its version.
Fixes issue: https://github.com/Azure/vscode-kubernetes-tools/issues/467
=> Format minikube status dependent on its version

src/components/clusterprovider/minikube/minikube.ts, src/extension.ts
Like suggested in https://github.com/Azure/vscode-kubernetes-tools/pull/575 this will remove the version dependency of the `minikube status --format` output and do the following:
* Use the first line of the output (.Host/.MinikubeStatus) for determining the status of Minikube (running/stopped)
* Instead of the notification bar (`showInfoMessage`) the whole output of `minikube status` is shown in the `Output -> Kubernetes` channel; So now users can see the status of the apiserver and kubelet, and the configuration of the kubectl.
@brendandburns: Like @itowlson already mentioned in https://github.com/Azure/vscode-kubernetes-tools/pull/575#issuecomment-509927412 I am changing the the original behavior of your work, and want to include you in the discussion whether this is ok or not.
=> Make "minikube status" version independent

schema/schema_enums.json, src/components/contextmanager/active-context-tracker.ts, src/components/contextmanager/active-value-tracker.ts, src/components/contextmanager/background-context-cache.ts, src/components/kubectl/proxy.ts, src/components/swagger/swagger.ts, src/extension.ts, src/kubectl.ts, src/yaml-support/schema-holder.ts, src/yaml-support/yaml-constant.ts, src/yaml-support/yaml-schema.ts, tools/save-swagger-enums.js
From k8s 1.15, the cluster Swagger includes custom resource types and their schemas if provided (subject to a feature gate in 1.15).  To take advantage of this, however, we need to fetch the schema definitions from the active cluster instead of using a local JSON file.
This is conceptually simple, but in practice is drags in a whole bunch of complexity.  `vscode-yaml` requests schemas synchronously, so we need to fetch schemas in the background, and present our best effort when a document opens.  The user can change clusters, or deploy/update CRDs, both of which affect the schemas available, and both of which can happen behind our back.  And even just fetching the Swagger requires some `kubectl proxy` which needed some more componentising.
So this PR brings in a subsystem for tracking the …
=> Use CRD schemas if available

README.md, package.json, src/components/config/config.ts, src/components/kubectl/logs.ts, src/components/logs/logsWebview.ts, src/components/webpanel/webpanel.ts
We've had some usability complaints and bug reports relating to displaying logs in a web view.  Ideally we'd like to address these issues to make the web view maximally useful for all our users, but this is a non-trivial piece of work.  It looks like the people who have raised issues were happy with the terminal-based display.  So as an interim measure this PR provides a settings option to revert to the old terminal-based display.  The web view remains the default, and we can and should continue working on it to address the issues our users have raised.
=> Option to display logs in the terminal

src/utils/array.ts
Fixes #613 by making `choose` method non-enumerable.
cc @MikeRalphson in case you want to sanity check this!
=> Avoid polluting Array prototype

src/components/contextmanager/background-context-cache.ts, src/yaml-support/yaml-schema.ts
We have a race condition in the per-cluster Swagger system.  Consider what happens when a document is loaded and triggers a series of requests for schemas.
* If the context name is not yet known, the bundled fallback Swagger is used.  This results in multiple lookups to the fallback Swagger (one per type in the document) which is fine.  Meanwhile, the context name is determined in the background, and when it arrives, we kick off a request to the cluster to get its Swagger.  The next time a document needs schema lookup it uses the now-available cached Swagger and all is well.
* But if the context name _is_ known (but the Swagger is not yet in the cache), then the cycle works a bit differently.  The first type name triggers a cache check for the context name.  The Swagger is not in the …
=> Fix starting multiple Swagger downloads

src/kubectl.ts, src/shell.ts
If the path to `kubectl` contained spaces, we were throwing an error because we did not quote the path before composing the command string and passing it to the shell.
Fixes #637.
=> Fix error if kubectl path contains spaces

src/yaml-support/schema-holder.ts
The Kubernetes Swagger does not include enum values.  To provide better code completion, we try to identify enum-ish types in the Kubernetes Go source code, create a file of those, and apply them to the relevant properties in the Swagger at run time.
However, we had a bug where if the schema specified an _array_ of the enumerated type, we were incorrectly applying the enum constraint to the _array itself_ rather than to the _items of the array_.  This led to a very confusing wiggly along the lines of `Value is not accepted. Valid values: "<the very thing that was in the YAML>".` because we were looking at the array and going "well, this array object is clearly _not_ a member of this set of strings."
Fortunately, this only affects two places, `NamespaceSpec.finalizers` and …
=> Arrays of enums need the enum on the item schema

README.md, src/telemetry-helper.ts
Our current telemetry is reporting a lot of 'indeterminate' cluster types.  This should happen only when there is an error - if the cluster is not Azure or Minikube, we should be reporting 'other', not 'indeterminate.'
This PR adds a 'non-determination reason' field to the telemetry, which distinguishes the cases of connection failure (refusal or timeout), credentials error, other `kubectl cluster-info` error and miscellaneous unknown errors.  This will help us to diagnose telemetry problems so that we can get a better sense of the environments in which the extension is being used.
As Minikube is being supplemented for local development by tools such as Kind and Microk8s, this PR also adds a new cluster type of 'local.'  Again, we are not trying to snoop into what people are using, but …
=> Telemetrise more info about cluster type inference

src/components/installer/installer.ts, src/extension.ts, src/kubeChannel.ts
Previously the version of Helm to download in 'install dependencies' was hardcoded.  This PR uses @bacongobbler's trick of querying the GitHub latest release page to find out which release it redirects to, and then downloads that.  If the query fails it still falls back to a hardcoded version rather than failing: this fallback has been updated to 3.0.0 (yay Helm 3).
=> Install latest version of Helm

src/helm.documentProvider.ts
Not sure whether something changed at the last minute in Helm 3, or whether I just missed this in the testing, but Inspect Chart on repo charts was broken: Helm 3 requires `helm inspect all` rather than just `helm inspect`.
=> Fix for Helm 3 inspect chart

package.json
Chart.lock replaces requiremens.lock in Helm 3.
=> Add syntax highlighting for Chart.lock

src/kuberesources.virtualfs.ts
Well, this is embarrassing.  `helm get` also requires the `all` subcommand under Helm 3...
=> Another place where we need to pass 'all' under Helm 3

src/components/config/config.ts, src/components/installer/installer.ts
Fixes #689.  See also #543.
TODO: There is still an issue where if `kubectl-versioning` is `infer` it assumes that `kubectl` will be available when needed, and so thinks it doesn't need to install it.  This is a false assumption, because we need a `kubectl` to work out the server version in order to download the right `kubectl`.  Raised this as #690.
=> Install Dependencies should use OS-specific config keys to record paths

buildsnippets/snippets.go, rawsnippets/deployment.yaml, rawsnippets/ifelse.tpl, snippets/helm.json
Update deployment API version to `apps/v1` in helm snippets, and add the `spec.selector` required field
After having updated the raw snippet, I generated a new `helm.json` file using the command `go run buildsnippets/snippets.go >snippets/helm.json`, and synced between the raw snippets and the `helm.json` file, since some of the previous changes were done in the `helm.json` file and not in the raw snippets, or vice verse.
Closes #675.
=> Update deployment API version to apps/v1

src/components/config/config.ts, src/components/installer/installer.ts, src/components/kubectl/autoversion.ts, src/kubectl.ts
At the moment, auto version (`kubectlVersioning: infer`) requires some (any!) version of `kubectl` in the PATH or settings, in order to query the server for its version and fetch the _actual_ kubectl for that cluster.  This is silly.  If we are going to magically get kubectl behind the scenes then let's make it work completely transparently.  With this PR, you can start the extension with NO KUBECTL AT ALL and it will go find one by SORCERY and you will be up and running as soon as your network can oblige.
The actual strategy it uses to find a 'bootstrapper' k8s is:
* If there's one around in the normal way (set in config or on PATH), use that.
* Otherwise, see if there are any autoversion directories containing `kubectl` binaries.  If there are, use one of those - it doesn't matter which …
=> If autoversioning doesn't have a kubectl to bootstrap from, find one and use it

rawsnippets/range-list.tpl, rawsnippets/range-map.tpl, rawsnippets/range-until.tpl, snippets/helm.json
We had a minor syntax error (text getting treated as variable references) in some of our Helm template snippets, which had been fixed in the generated `snippets/helm.json` but had not been fixed in the templates from which the JSON was generated.  This meant that when someone did things right and regenerated the JSON, which they did in #676, the error reappeared.
This PR fixes the error at source, so that future regenerations should not cause this to recur.
=> Fix snippet syntax warning

debug-on-kubernetes.md, package-lock.json, src/debug/debugProvider.ts, src/debug/debugSession.ts, src/debug/debugUtils.ts, src/debug/dotNetDebugProvider.ts, src/debug/javaDebugProvider.ts, src/debug/nodejsDebugProvider.ts, src/debug/providerRegistry.ts, src/debug/pythonDebugProvider.ts
1. Prerequisites
* [C# for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) extension must be installed on local machine.
* `ps` must be available on the docker container. `ps` is used to try and autoselect the process id to debug. It is also used by the `C#` extension to look up processes for the process picker if there is more than one dotnet process running. You can install it by running the following command on the container:
`apt-get update && apt-get -y install procps`
* [`vsdbg`](https://github.com/OmniSharp/omnisharp-vscode/wiki/Attaching-to-remote-processes) must be installed on the container. You can download it by running the following command on the container.
https://github.com/OmniSharp/omnisharp-vscode/wiki/Attaching-to-remote-process …
=> Add dotnet attach debugging support

package-lock.json, package.json, src/api/contract/cluster-explorer/v1.ts, src/api/implementation/cluster-explorer/v1.ts, src/components/clusterexplorer/explorer.ts, src/components/clusterexplorer/node.configurationvalue.ts, src/components/clusterexplorer/node.context.ts, src/components/clusterexplorer/node.folder.crdtypes.ts, src/components/clusterexplorer/node.folder.resource.ts, src/components/clusterexplorer/node.folder.ts, src/components/clusterexplorer/node.helmrelease.ts, src/components/clusterexplorer/node.message.ts, src/components/clusterexplorer/node.resource.ts, src/components/clusterexplorer/node.ts, src/components/config/config.ts, src/components/kubectl/kubeconfig.ts, src/components/kubectl/watch.ts, src/explainer.ts, src/extension.ts, src/kubectlUtils.ts, src/kuberesources.ts
This is a POC based on https://github.com/Azure/vscode-kubernetes-tools/issues/647
This PR allows the extension to update Kubernetes Clusters View content automatically when something on cluster changes. There are 2 ways to set up a watch on resources: by using the action in the context menu or by declaring the kind of resources to watch in the settings (vs-kubernetes.resource-to-watch).
Currently the watch function is supported by `folder.resource` and `resource` nodes.
The watch is managed in a way that it is active only if the node of the resources we want to watch is expanded. Once the treeitem is in a collapsed state the watch is removed. This way we prevent to call the refresh tree method for resources user isn't looking at.
The refresh is made on single node to avoid refreshing the …
=> Update Kubernetes Clusters View content automatically when something changes

debug-on-kubernetes.md, src/debug/dotNetDebugProvider.ts
C# extension has changed its name from "ms-vscode.csharp" to "ms-dotnettools.csharp", this means all extensions depending on it needs to be updated and i.e. all repositories with extension.json containing
```json
"recommendations": [
"ms-vscode.csharp"
]
```
or you get errors like
=> ms-vscode.csharp to ms-dotnettools.csharp

src/components/kubectl/dashboard.ts, src/kuberesources.objectmodel.ts
After the Kubernetes is upgraded on aks, the port of dashboard is changed and https is enabled. The port is hard-coded in the extension so it creates incorrect proxy connection when execute the command "Kubernetes: Open Dashboard".
This PR change the logic from hard-coded to retrieve the port number and url scheme from pod metadata.
=> Get aks dashbaord port number and url scheme from metadata

debug-on-kubernetes.md, src/components/config/config.ts, src/debug/dotNetDebugProvider.ts
Added the possibility to define a sourceFileMap
entry to the dotNetDebugProvider in order to fix an issue
with non working breakpoints for the Kubernetes: Debug (Attach)
operation
=> #Issue 724: breakpoints in vscode not working as expected when debugging in docker container 

src/debug/nodejsDebugProvider.ts
On my machine I kept getting the error: "Unable to set Node.js in the container to inspect mode".
After debugging the extensions, I saw the error from `kubectl` was an unterminated string after `-c`. Changing to double quotes fixed it for me.
=> Fix attach to node.js

debug-on-kubernetes.md, src/debug/dotNetDebugProvider.ts
For paths nested deeper in filesystem it should use the regex-version of `replace` to replace all occurences of the backslash.
I also updated the sample docs about `vs-kubernetes.dotnet-source-file-map` because it was pretty unclear to me that a string to the path is expected.
@mattjanson do you agree with the description?
=> Fix for Pullrequest #736: replacing all occurences of backslash with regex

src/helm.documentProvider.ts, src/helm.exec.ts, src/shell.ts
Fixes a Repo Explorer issue if user adds a malicious repo and clicks on a malicious chart.
=> Validate strings from Helm repo before passing to shelljs

README.md, package.json, src/binutilplusplus.ts, src/components/config/config.ts
Finally i was able to replicate the error users have by installing stuff with snap. #770 #522 
Did i find a fix? Apparently yes. Did i find out the reason why it doesn't work? No, absolutely not lol. 
This is what i got if i try to execute the command without the hack
In Unix systems this solution should always work (i guess in Windows it fails as there is no `cat` cmd) but i added an extra setting so snap users can enable this because i am not sure if i'm forgetting something. This way the extension will keep working as before for others.
=> Added a hack to make kubectl works if installed with snap

src/helm.funcmap.ts
The tooltip of the helm-template function [has](https://helm.sh/docs/chart_template_guide/function_list/#has-musthas) had the parameters $item and $list in the wrong order.
=> Fixes the tooltip of the helm-template-function 'has'

src/yaml-support/yaml-locator.ts, src/yaml-support/yaml-util.ts
it resolves #801 
This PR handles the error thrown by the yaml-parser lib we use here so kubernetes-tools extension doesn't prevent other extensions from registering other contributors for yaml schemas. I also opened an issue in the lib as well https://github.com/andxu/yaml-parser/issues/1
=> Do not fail if an error occurs during yaml parsing

src/yaml-support/jsonalike-symbol-provider.ts
it fixes #359 
The fix is similar to https://github.com/Azure/vscode-kubernetes-tools/pull/360. We forgot to switch from `safeLoad` to `safeLoadAll` here as well. By using `safeLoad` only the first resource was taken in consideration.
=> Fixes linter issue with multi object file

src/components/clusterexplorer/explorer.ts
It resolves #764 
In the issue there is also a request to add an "expand all" button. By looking at the vscode api documentation it looks like we can only expand to 3 levels. It should be enough for this extension but i wonder if we want that behavior. Do we really want to expand all tree? Or it is enough to just expand the first/second level (e.g to see all possible group resources such as pods/deployments/jobs... and the user then decide which one to expand)? I think it's better to create a new issue and discuss how it should behave.
=> Add collapse all button

README.md, package.json, src/components/config/config.ts, src/components/kubectl/namespace.ts, src/extension.ts, src/kubectlUtils.ts
it resolves #777 
This PR adds two items to the status bar: one which displays the current context and another one which displays the current namespace. (in the example below minikube is the context, tektontest the namespace)
By clicking on the context, the user can switch it (a quickpick shows up with a list of possible contexts).... the same for the namespace item.
Users can hide one or both items by using the optional settings in the extension.
=> add status bar items for viewing/changing current context and namespace

src/components/installer/installer.ts
* Restrictive installer permission for kubectl. 
Probably more conformance to something like this: https://github.com/Azure/vscode-kubernetes-tools/blob/master/src/components/installer/installer.ts#L137 
Thanks, and cc: @itowlson and @squillace for eyeballing and thoughts. 🙏 💡
=> Restrictive installer permission for kubectl.

CHANGELOG.md, package.json
This is basically the bundling change, plus a couple of nonfunctional changes (documentation fixes).  I'm suggesting we publish this as its own release despite the lack of new features, because that way we can easily detect the impact of this change in isolation, and roll back without withdrawing features if it turns out to be a disaster!
=> Publish 1.2.3

.github/workflows/main.yml, docs/README.md, docs/maintenance/README.md
This is related to https://github.com/Azure/vscode-kubernetes-tools/issues/728
The workflow has to be triggered manually and it does almost all the job needed to publish the extension to the marketplace.
- Build the extension
- Check that version used in the `package.json` file is mentioned in `changelog.md`
- Create a new release (if another one with the same version exists, it fails)
- Publish it to the marketplace
The only secret required is the marketplace token.
The only edit we need to make inside the project is about the changelog, a version should be written like `## [x.x.x]` because the action follows this convention.
By having this workflow in place we can also make a release when Ivan is busy on other projects. We just need to agree when a new release can be made.
Only thing …
=> Automate release process (#728)

src/api/implementation/cluster-explorer/common.ts, src/api/implementation/cluster-explorer/v1.ts, src/api/implementation/cluster-explorer/v1_1.ts
There is a lot of shared behaviour in the Cluster Explorer V1 and V1.1 API implementations (reflecting their significant overlap in the API surface).  We have a new API version coming down the line for a new tree layout, and I am hoping to add some new node sources before too long, which would be another API version.  So it would be good to centralise so that we can more easily review only what has changed rather than reviewing implementations files that are marked entirely as new code.
=> Centralise Cluster Explorer API implementation

src/api/contract/cluster-explorer/v1.ts, src/api/contract/cluster-explorer/v1_1.ts, src/api/implementation/cluster-explorer/common.ts
When Helm release history was added the the cluster explorer, the v1 and v1,1 API contract files were edited to surface this node type, putting them out of sync with the previously existing contract.  This was unintentional and an error: existing API contracts never change, and the files should always reflect those pre-existing contracts.
This PR reverts the Cluster Explorer API contract files to their conditions before the edit, and restores them to being in sync with the previously existing contracts.
As a future enhancement, we should consider keeping golden versions of the API contracts in the tests folder, and verifying that the files in `src/api/contracts` have not changed from there, with a message conveying that the golden versions must not be changed and a new API version must be …
=> Revert v1 and v1.1 APIs to their contracts

src/helm.funcmap.ts
required and join were inaccurate; [join isn't variadic](http://masterminds.github.io/sprig/string_slice.html#join), and [required requires a message](https://helm.sh/docs/howto/charts_tips_and_tricks/#know-your-template-functions)
=> Fix some completion item descriptions

package.json, src/components/config/config.ts
It is undesirable for workspace-level configuration to specify tool paths, because those tool paths are unlikely to be portable across different clones of the workspace.
Fortunately, VS Code allows you to mark configuration settings as `machine` or `user` so that they are picked up only from global settings and ignored at the workspace level.
Unfortunately. we long ago bundled all our settings into one settings object.  And VS Code would only let us mark that _object_ as `machine` or `user`.  We can't mark individual properties of the object.
So this PR declares some new top-level properties for tool paths, which are marked as `machine`.  The old object properties are accepted for compatibility, but only at global level; workspace level settings are now explicitly ignored.
(As a bonus, …
=> Ignore tool paths at workspace level

package.json
I upgraded the VS Code types as part of the smoke test PR, but this put them out of sync with the VS Code engine declaration, which caused issues in packaging which weren't caught in the PR cycle.  This puts things back in sync.  And now everything will just work first time.
=> VS Code engine and types were out of sync

webpack.config.js
it resolves #897 
@itowlson found this https://webpack.js.org/configuration/node/#node__dirname . Now the `__dirname` is resolved to `/` and it probably fails because it doesn't have permission to write the proxy file there. By adding this rule `__dirname` should be resolved  like before. Try it whenever you can.
=> add webpack __dirname rule

src/components/installer/fixwriteablebinaries.ts, src/components/installer/installationlayout.ts, src/components/installer/installer.ts, src/extension.ts
We had an issue where binaries we installed were too broadly writeable.  That is now fixed, but users who allowed old versions of the extension to do an install will be left with poorly configured files.
This fix checks the extension's tool installation directory at startup and fixes any executable files to be user-writeable only.  To avoid performing this check on every startup, it records if there has been a successful pass and skips the directory walk if so.
=> Binaries installed with wrong permissions should be fixed

package.json, src/extension.ts, src/helm.documentProvider.ts, src/helm.exec.ts, src/helm.ts, src/utils/preview.ts
This PR follows the enhancement request #891 and implements a new command `Generate values.yaml` for Helm Repo Explorer which generates a `values.yaml` file for the Helm chart. 
The primary use case for this `values.yaml` file is syntax highlighting and generation of editable `values.yaml` file which can enable customization of Helm chart installation.
Since this functionality is closely related to Helm Inspect Values I have implemented this as an extension of the same. Happy to provide alternate implementation if necessary.
=> Adding support for syntax highlighting for Helm Inspect Values

package.json
values.yaml is for user-specified values rather than a Helm chart specification. Associating with helm-template causes issues when using JSON schema validation, as noted in #146, redhat-developer/vscode-yaml#196, and others.
=> Remove values.yaml association with helm-template

src/components/config/config.ts
**Description:**
This PR fixes the issue where the dependencies(kubectl, helm, minikube) are not being downloaded in remote-containers automatically. Currently in #543, manual workaround are specified to unblock the users but this PR would remove the need to have a manual workarounds.
**How it is being fixed:**
Once the install dependencies button is clicked, on a fresh machine the binaries are being downloaded to /home/username/.vs-kubernetes/tools/< toolname >/< toolBinary >. After the download is completed (for example in installKubectl ), the path of the tool is updated in the config values at Global, Workspace & WorkspaceFolder level using `addPathToConfig`.
Previously the values are being retrieved from the custom config values.
=> Read the install locations from User and default configuration to decide whether the dependencies are installed or not

log-colors-rules.json, src/components/logs/app/index.html, src/components/logs/app/main.js
it fixes #942 
This patch fixes some performance issues discovered while reading big logs (>80k rows, size 10MB).
The content loaded is now calculated based on where the user is reading and only a part of the full content is displayed (~500rows). This prevent the UI from freezing while highlighting all the content.
After the user stops scrolling the viewer calculate which rows should be displayed and render them.
All schemas have been merged based on their final highlighting color to reduce their numbers (and so the loops), switched from inline-style to css classes and replaced arrays with objects.
=> Improve performance log viewer

src/components/swagger/swagger.ts, src/kubectlUtils.ts, src/yaml-support/schema-holder.ts
This resolves #917 
Until now the plugin only downloaded the swagger json from the active cluster which contains minimal schemas for custom crds. An example is the camel-k operator as mentioned in #917. The minimal schema for the kameletbinding type is 
```
{
"id": "camel.apache.org/v1alpha1@KameletBinding",
"apiVersion": "camel.apache.org/v1alpha1",
"kind": "KameletBinding",
"type": "object",
"name": "org.apache.camel.v1alpha1.KameletBinding"
}
```
while the crd on the cluster contains the actual schema 
```
"versions": [
{
"additionalPrinterColumns": [
{
"description": "The Kamelet Binding phase",
"jsonPath": ".status.phase",
"name": "Phase",
"type": "string"
}
],
"name": "v1alpha1",
"schema": {
"openAPIV3Schema": {
"description": "KameletBinding is the Schema for the kamelets binding …
```
=> Fetch custom crd schemas from active cluster

package.json
These aren’t Helm templates. They are regular yaml files.
=> Remove chart.yaml and requirements.yaml from languages

debug-on-kubernetes.md, package.json, src/components/config/config.ts, src/debug/dotNetDebugProvider.ts
Fixes #962
* add new option `vs-kubernetes.dotnet-vsdbg-path` to set path to vsdbg inside container
* change default path to `vsdbg` from `/vsdbg/vsdbg` to `~/vsdbg/vsdbg`
=> Provide ability to config path to vsdbg

CODE_OF_CONDUCT.md, CONTRIBUTING.md, GOVERNANCE.md, OWNERS.md, README.md
CNCF commented that we did not have a readily available maintainer list.  This PR captures the current state in `OWNERS.md` and also adds some rudimentary governance info in `GOVERNANCE.md`.
These are substantially copied from the Porter project so reviewers please double-check in case I left mentions of Porter in there!
cc @gorkem for additional Red Hat perspective and because I know this is something you've tried to nudge us to do better in the past (some of the governance doc is cribbed from your contributor documentation - thanks!).
=> Add maintainer list

package-lock.json, src/helm.completionProvider.ts
The PR uses the `vscode.FileSystemWatcher` API to refresh the helm values cache whenever `values.yaml` is saved. With these changes in place, it is no longer necessary to reload VSCode to include new values in autocompletion.
=> Watch for changes in helm's values.yaml

src/debug/dotNetDebugProvider.ts
Using shell allows expanding `~`.
=> Use `/bin/sh` to run debugCommand in dotnet (#1002)

src/helm.completionProvider.ts
Do not write message to VSCode Helm Output every time Helm values have been refreshed. Fixes #1026.
=> Do not log values refresh message

debug-on-kubernetes.md, src/debug/dotNetDebugProvider.ts
Previous dotnet debugging implementation looked for processes with
dotnet name only. Since .NET Core 3.1, .NET applications may have a native
executable to launch the app with name that differs from dotnet.
The new implementation doesn't set process id when call vscode-omnisharp
debugger. Now, vscode-omnisharp is used for executing `ps` and showing
vscode UI for choosing process.
=> Shift dotnet process identification to vscode-omnisharp (#1003)

README.md
the repository moved from "Azure" to "vscode-kubernetes-tools" organisation so the links need updating
=> Fix dead links since repo move

src/v1.ts
One of the referenced documents have been moved to a sub-folder and many links were broken. 
I also made an update to the v1.volume sub-section based on the official Kubernetes documentation.
=> Fix dead links in v1 and update v1.volume sub-section

site/config.toml
Css link is broken as it keeps pointing to azure. This should fix the css issue
=> Fix site baseURl

src/helm.exec.ts
This is a strange PR and I would have no qualms with it being rejected.
Unfortunately excluding `**/node_modules/**` from `vscode.workspace.findFiles(...)` calls is somewhat necessary to prevent excessive CPU usage when this extension is installed and users open a large frontend project in VS Code. `findFiles` searches the entire repo by default, even `.gitignore` files.
One comment from a VS Code member recommends extensions exclude `node_modules`, since a proper fix to the `findFiles` API would be a breaking change: https://github.com/microsoft/vscode/issues/75314#issuecomment-503195666
This seems to be somewhat standard, even in extensions that have nothing to do with Node.js. For example:
- Searching `workspace.findFiles` in the `microsoft/vscode` repo shows almost every usage …
=> Exclude **/node_modules/** from Chart.yaml searches

package.json, src/components/config/config.ts, src/kubectlUtils.ts, src/yaml-support/schema-holder.ts
it resolves #1050 
This adds a setting to allow users enabling/disabling the crds fetch when the plugin tries to download all custom schemas. If the general setting is undefined the plugin uses the crds count to decide if to proceed or not and ask the user for confirmation. @itowlson
=> add setting to disable fetching all crds

README.md, package.json, src/components/config/config.ts, src/components/logs/app/index.html, src/components/logs/app/main.js, src/components/logs/logsWebview.ts
Whenever I view the logs of a pod, I always set the same options pretty much. ^-^'
This just creates some global settings which sets the default log viewer options.
For now, it only covers `follow`, `timestamp` and `wrap`.
I'm considering doing others later, but figured for now this would be nice.
It looks to me (though I didn't check manually) that the `reset()` method wasn't resetting the `wrap` checkbox anyway, so this also fixes that.
* Partially resolves x https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1058#issue-1204480246
* I can also make an option to run by default on viewing logs too after/if this is merged.
=> feat: add log viewer options

README.md, package.json, src/components/config/config.ts, src/components/logs/app/main.js, src/components/logs/logsWebview.ts
Adds a setting to automatically run the log viewer using the default settings once the viewer has finished initializing.
* Partially solves x https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1058
* Still missing a setting to scroll to bottom by default.
=> feat: add option to run automatically

src/components/clusterexplorer/node.folder.crdtypes.ts, src/kubectlUtils.ts, src/kuberesources.objectmodel.ts
This addresses a problem that happens:
- on Windows
- on a cluster with a large number of CRDs (~80 in my case)
**Symptom**
The UI becomes completely unresponsive for well over a minute, in a couple of places:
- immediately *after* the new (#1059) CRD popup appears (making it impossible to make the choice about fetching CRDs until it's recovered).
- after expanding the 'Custom Resources' item.
These are both times when the code invokes `kubectl get crd -o json`.
Interestingly, nothing much seems to be happening at the time it hangs. Both the `kubectl` call and the JSON parsing have already completed. It appears to happen on the first `await` after those things have happened, so my best guess is that parsing the massive json array created a lot of detritus in memory, and the …
=> Fix unresponsive UI after getting CRD json

src/components/logs/app/index.html, src/components/logs/app/main.js
* "key words" → "keywords"
* https://www.wordnik.com/words/keyword
* https://www.dictionary.com/browse/keywords
* https://en.wikipedia.org/wiki/Keyword
I removed the "all" option, as I felt this was unnecessary.
A more intuitive way to handle this is to not apply a filter if the text boxes value is empty rather than a dedicated `all` value. An empty text box, similar to the value `-1` in a numerical text box, is generally implied as unset. (Even if a user were to interpret it otherwise, an empty string or regex matches all logs.)
Now when a user wants to filter logs, they only have to set 1 field instead of 2. (Unless they want to use a different filter mode.)
I firmly believe this improves the user-experience with the extension, but am happy to revert that if maintainers disagree.
=> rework: make "that match" default option

src/components/logs/app/index.html, src/components/logs/app/main.js
Word wrap only _partially_ wrapped lines before.
Before it would only split lines by word boundaries (i.e. whitespace or hyphens), for example, long words or minified JSON would still extend over and require a horizontal scrollbar to view the full log. (Which kinda defeats the point of word wrapping since the goal is to avoid horizontal scrolling.)
This adds `overflow-wrap: anywhere` which tells the view that it's ok to split in the middle of words. Now users won't experience a horizontal scroll bar at all when word-wrap is enabled!
More info:
* https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
* https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1076 Originally a part of this, but was split off.
=> fix: make word-wrap actually wrap lines

README.md, src/components/installer/installationlayout.ts, src/components/kubectl/autoversion.ts
The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) specifies various user directories for applications to store data. There are a lot of [good reasons](https://xdgbasedirectoryspecification.com) to support this, and this PR adds support in a backwards-compatible way
- This PR adheres to the spec by creating the `vs-kubernetes` directory in `~/.local/state`, but _only if_ a directory has not been created at `~/.vs-kubernetes` _and_ the current platform is Linux
- In the case where we can follow the XDG Base Directory Specification, users can customize where the `vs-kubernetes` directory is created with the `XDG_STATE_HOME` variable. If the env var is empty or if it's a relative path (as per the spec), the default of …
=> Use XDG Base Directory variables when creating the base installation directory

debug-on-kubernetes.md, package-lock.json, package.json, src/components/config/config.ts, src/debug/dotNetDebugProvider.ts, src/debug/pythonDebugProvider.ts
Add the `justMyCode` option to the debug configuration when debugging [.NET](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#just-my-code) and [python](https://code.visualstudio.com/docs/python/debugging#_justmycode) with `debug (attach)`
The `justMyCode` property instructs the debugger to *not* skip loading external code.
=> add justMyCode debug option

LICENSE, package.json, site/package.json
The Kubernetes extension is becoming a CNCF project.  As part of this, the CNCF requires us to change the licence to Apache 2.0.
This issue asks our contributors, who contributed their work under the MIT licence, to consent to the project being relicensed as Apache 2.0.
Thanks to all of you!
@apupier 
@itowlson 
@pantosha 
@flowftw 
@flynnduism 
@evidolob 
@lstocchi 
@ivolzhevbt 
@brendandburns 
@rakeshvanga 
@ezramorris 
@markszente 
@shreyaskarnik 
@Persistent13 
@bacongobbler 
@amsoedal 
@Techmaster21 
@dev01d 
@Tatsinnit 
@bnookala 
@jo-goro 
@bfitzpat 
@ltsbkuster 
@aelij 
@mattjanson 
@gorkem 
@hermanho 
@devlead 
@tedchamb 
@amirschw 
@remcohaszing 
@ahmadalli 
@mabouchacra 
@antonyveyre 
@ederst 
@alexkreidler 
@medzin
@azatsarynnyy
@khvn26 
@meeech 
@Flanker32 
@yehiyam 
@oik741 …
=> Change licence to Apache 2

src/debug/debugSession.ts
This change sets the target kubernetes pod's name as the default name for the debug session when using the "Debug (Attach)".
Currently, by passing in 'undefined' it's falling back to a numeric datetime value as the debug session name and when attaching debuggers to multiple containers this becomes very confusing for the user.
=> Set debug session name to pod name on attach

src/components/clusterexplorer/resourcekinds/resourcekind.pod.ts, src/components/kubectl/logs.ts, src/components/logs/app/main.js, src/components/logs/logsWebview.ts, src/extension.ts, src/kubectlUtils.ts, src/kuberesources.objectmodel.ts
I have a need to see the logs for initContainers while running and after they have completed.  This also makes the pod status color yellow for notReady while the initContainer is running as opposed to red which may make the user think there's an error condition.
=> added limited support for initContainers (logging)

package-lock.json, package.json, src/components/logs/app/index.html, src/components/logs/app/main.js, src/components/logs/logsWebview.ts, src/components/logs/webpack.config.js
=> fix: handle ANSI color codes in log webview (#1164)

src/yaml-support/yaml-locator.ts
After digging a bit i found out that the node-yaml-parser is responsible of the memory leaks detected in https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1170 . If the yaml file is not formatted correctly it start looping in a while and never ends.
It would be great to have this fixed in the lib itself but it seems an abandoned project. I opened an issue 3 years ago about another bug and nobody replied. So i guess this is a fastest solution. Maybe we should find another lib to replace this one.
https://github.com/andxu/yaml-parser
So as a temporary solution, i added another parsing using the yamljs lib. If the yaml is not formatted correctly it fails and skip the node-yaml-parser, otherwise it is called and it should not fail.
The fix can be validated by using the …
=> fix: detect errors in yaml file before actually parse it with node-yaml-parser lib (#1170)

package.json
In our small development team I noticed our interactions with K8S commonly boils down to three tasks: describing a pod to see its status, viewing its logs (and not needing to type a lengthy `kubectl` command!) and occasionally jumping into a terminal to play with args for probes manually.
This PR adds those commands to the inline group to make them easier to reach than the context menu:
(If this isn't desirable feel free to close! 🙂)
=> Add inline buttons for describe, logs, and terminal

src/debug/goDebugProvider.ts
It looks like the inputs field doesn't actually work. By looking at the examples on the vscode documentation I think it should be one level up the debug configuration but it's not possible if we create it by code.
Something like
```
{ 
type: "go",
request: "attach",
},
inputs: {
...
}
```
but we have 
```
{ 
type: "go",
request: "attach",
inputs: {
...
}
},
```
So this patch adds a new step to ask the user for the remote root path.
Another thing is that it was missing the current workspace variable.
it resolves #1184 and #1114 
To test it i used the `bacongobbler/helloworld-go` project. 
So cloned the repo, init/build the app. Created a Dockerfile having the dlv to debug it. Kubernetes run to push it on cluster, then attach debug.
```
FROM golang:1.20-buster AS builder
WORKDIR /app
RUN go …
```
=> fix: debug attach not working with go app (#1184)

README.md, src/components/config/config.ts, src/debug/debugSession.ts, src/extension.ts, src/utils/interpolation.ts, test/suite/utils/interpolation.test.ts
This PR allows to handle a set of vscode predefined variables when used as values in the extension settings  -> https://code.visualstudio.com/docs/editor/variables-reference
This should resolve https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/940 and https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1141
Now the user could write a setting like 
```
"vscode-kubernetes.kubectl-path": "${userHome}/my_custom_kubectl_folder/kubectl"
```
The interpolation function has been taken from https://github.com/DominicVonk/vscode-variables and updated. The license allowed it.
I couldn't import the library as it was very old and not maintained apparently. It relies on the old vscode dependency which break this one when imported (the k8s-tools depends on …
=> feat: handle predefined vscode variables in extension setting (#940)

src/components/logs/app/main.js, src/extension.ts
it resolves #1187 
There was also an issue in the log viewer. @Tatsinnit Please give a look at everything that comes to your mind that works with containers. https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1150 added some misbehavior apparently. Hopefully I tracked all issues. If you can do some other testing it would be better.
I guess we should make a new release when this is merged.
=> fix: trim container name and filter empty ones (#1187)

README.md, package.json, src/components/config/config.ts
Configuring custom tool paths was not working correctly.
#1181 introduced a bug which causes the `baseKey` to not be handled at all.
Also, a configuration property in vscode cannot be a string and a object (with nested properties) at the same time.
eg. if you have both keys `vscode-kubernetes.kubectl-path` and `vscode-kubernetes.kubectl-path.linux` set, vscode will not return the nested `.linux` property at all. Therefore, it's better to use properties at the same level so that the overrides can work correctly (by changing `.` to `-`).
Also corrected the README.
=> Fix tool path configuration handling

src/shell.ts
Set kubectl commands to 'silent' because otherwise this extension makes the debug console in vscode unusable
=> disable kubectl command output in the debug console

src/components/logs/app/index.html, src/components/logs/app/main.js
The current log view has overflow issue where the beginning of the logs can be hidden by the header when the width of the panel is small enough to cause the header to take more space than 90px:
This PR reworks the layout structure to use tables and flexboxes to create a more cohesive and responsive experience:
https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/assets/549323/13997c39-69d3-4d5a-95fd-f545f70e6f91
=> Create a more responsive/adaptive layout for the log view

.github/workflows/build-dev.yml, package-lock.json, package.json, test/runTest.ts
~~Test redo for the Tim's work. Along with a key test failure which is happening due to the deprecation of `vscode-test`~~
* This PR also constitute the fix for the test because the `vscode-test` is deprecated. https://www.npmjs.com/package/vscode-test 
~~This PR also take care of #1232  which had some signo-off issue.~~ 
~~Hence an fyi to @timheuer and thank you so much to #1232 - a gentle ping as fyi and **your contribution** is `cherry-picked` hence it will be maintained against this repo. ❤️☕️🙏~~
~~It takes care of this sign-off over-write which makes the last release as part of the other PR.~~
Thank you again and gentle - ❤️🙏 cc: @squillace , @gambtho and @peterbom for eye balling, there is whole lot of dependency update needed which I will align next.
Alsso just for context …
=> Test fixes.

.github/dependabot.yml
This PR caters the `package-ecosystem` for the Dependabot for being `npm`.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
Currently Dependabot is not happy because of the issue:
> The property '#/updates/0/package-ecosystem' value "" did not match one of the following values: npm, bundler, composer, devcontainers, maven, mix, cargo, gradle, nuget, gomod, docker, elm, gitsubmodule, github-actions, pip, terraform, pub, swift
For sample this should trigger updates like this: https://github.com/Tatsinnit/vscode-kubernetes-tools/pulls associate to #1276 
Thanks. ❤️🙏 fyi : @squillace , @hsubramanianaks , @qpetraroia fyi @gambtho
=> Fix the package-ecosystem from empty to npm.

src/components/logs/app/index.html, src/components/logs/app/main.js
This PR fixes #1253 by replacing all instances of `vscode-select` with `vscode-single-select`.  #1265 introduced the #1253 bug by upgrading `@bendera/vscode-webview-elements` which claims in the release notes that `0.17.2` shouldn't have Single/Multi Select until v1.0.0 in the new NPM package (https://www.npmjs.com/package/@vscode-elements/elements), but nevertheless, this PR does fix the issue.
A separate issue/effort should likely be considered to upgrade `@bendera/vscode-webview-elements@0.17.2` to `@vscode-elements/elements@latest` (where latest is `1.3.0` at the time of writing).
=> Use `vscode-single-select` instead of `vscode-select`

package-lock.json, package.json
This PR fixes the build break cause by #1285 and ~I also try to update unzipped in same PR and see if it fixes 1293~ 
~I can always segregate this PR into 2 as well~ This is PR is only for the vscode engine fix, and we will handle Unzipper update separately. Thanks heaps. fyi: @qpetraroia, thanks.
=> fix dependabot build break vscode.

package.json, src/components/config/config.ts, src/logger.ts
This channel may be annoying a bit, especially when your yaml in values is not valid. supress-output option makes a user able to turn showing output Helm channel off
fixes #1137 #1100 #929 #907
=> feat: add an option to disable Helm channel output

package-lock.json, package.json, src/components/clusterexplorer/node.folder.resource.ts, src/components/clusterexplorer/node.resource.ts
This PR is to fix #1344 key things is that:
The syntax case "A" || "B" is not valid in switch statements. We need to list each case individually, which is done here. Hence the other changes. One such example: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch#taking_advantage_of_fall-through 
Thank you folks.,
=> Fix typescript update for dependabot and relevant changes.

CHANGELOG.md, package-lock.json, package.json
This PR is intended to open release for version `1.13.17` which carries following key things along with various dependant PR.
* feat: add an option to disable Helm channel output (#1208)
* dependabpt PR's
* Remove old site scaffolding project and Update/package dependencies (#1277)
* Added snippet for ReplicaSet (#1268)
* Prune and upgrade npm package dependencies (#1265)
* Use vscode-single-select instead of vscode-select (#1294)
* Fix the ubuntu failure. (#1279)
For testing reasons here is the VSIX please, thanks heaps. [vscode-kubernetes-tools-1.3.17-test.zip](https://github.com/user-attachments/files/17290561/vscode-kubernetes-tools-1.3.17-test.zip)
Thanks heaps, and :heart: gentle fyi to @qpetraroia , @hsubramanianaks , @ReinierCC & @tejhan cc: @squillace + @gambtho
=> Publish release 1.13.17.

CHANGELOG.md, package-lock.json, package.json
This PR is intended to open release for version `1.13.18` which carries following key things along with various dependant PR. 
Most importantly this fixes a broken extension from previous release.
* Fix clipboardy/webpack issue - breaking release 1.3.17 #1355
Thanks heaps, and ❤️ gentle fyi to @qpetraroia , @hsubramanianaks , @ReinierCC & @tejhan cc: anime-shed , @kejatura-dev, @corneliusroemer, @okgolove, @metaphy6 , @verhelstq, @squillace + @gambtho ❤️
=> Publish release 1.3.18.

package-lock.json, package.json
This PR is raised ignorer to properly fix dependant update: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1362 
with the vscode version update it is required to update the `engine` otherwise latter build will fail.
thank you so much.
=> Fix update with engine udpate.

.github/workflows/build-dev.yml, .github/workflows/main.yml
These changes are made in correlation with the following changes coming soon in the GH actions permissions. Please take a kind look. ❤️🙏☕️
* https://docs.opensource.microsoft.com/github/apps/permission-changes/
To start with going with the most safest option with read only permission, for `publish` we need the `write for content`. Given this will spread pretty soon lets try this out and I will gradually open similarity changes in other repos I know.
For Sample test if we do `content: read` for publish we will get some error like this which I tested in my fork for other project.
Thank you. ❤️🙏
=> Changes in correlation with new GH Action Permission Changes.

CHANGELOG.md, package-lock.json, package.json
This PR is intended to open release for version `1.13.19` which carries following key things along with various dependant PR.
* Simple clipboard implementation. (#1361)
* Dependabot PR's
* Fix update with engine udpate. (#1369)
* Fix the vscode update. (#1384)
* Changes in correlation with new GH Action Permission Changes. (#1247)
* Fix the client-node update. (#1390)
* Fix:Init container logs not working (#1391)
* Fix build break. (#1419)
* Update owner.md for Current Active Users and Project Collaboration (#1431)
Thanks heaps, and ❤️ gentle fyi to (Lets please get this quick spin around windows and other O/S please)  @hsubramanianaks , @ReinierCC, @tejhan &  @qpetraroia  ❤️ cc: @squillace 
**VSIX for quick test:** 
*  [vscode-kubernetes-tools-1.3.19-test.vsix.zip](https://github.com/user …
=> Publish release 1.13.19

CHANGELOG.md, package-lock.json, package.json
This PR is intended to open release for version `1.13.20` which carries following key things along with various dependant PR.
* Dependabot PR's
* Add the AKS logo to any AKS cluster. (#1440)
Thanks heaps, and ❤️ gentle fyi to (Lets please get this quick spin around windows and other O/S please)  @hsubramanianaks , @ReinierCC, @tejhan &  @qpetraroia  ❤️ cc: @squillace 
**VSIX for quick test:** 
[vscode-kubernetes-tools-1.3.20-test.vsix.zip](https://github.com/user-attachments/files/18623971/vscode-kubernetes-tools-1.3.20-test.vsix.zip)
=> Publish release 1.3.20

src/components/clusterprovider/azure/azure.ts, src/components/clusterprovider/azure/azureclusterprovider.ts
This PR removes the Azure Container Services options which no longer exists and replaced with Azure Kubernetes Services. 
Only AKS and minikube options are provided now. Please reach out if you have any questions. Thank you all. 
Tested in Ubuntu, works well cc: @qpetraroia @Tatsinnit
=> remove acs and it's options

package-lock.json, package.json
This PR fixes https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1472 the possible issue which usually raise when the vscode engine update is not done
one such failure example is something like this for example:
thanks!
=> Update vscode with engine update.

CHANGELOG.md, package-lock.json, package.json
This PR is intended to open release for version `1.13.22` which carries following key things along with various dependant PR.
* Dependabot PRs
* feat: warn about lack of CPU and memory requests (#1493)
* Fix: broken telemetry due to old logic in place. #1500
Thanks heaps, and ❤️ gentle fyi to (Lets please get this quick spin around windows and other O/S please)  @ReinierCC, @tejhan, @bosesuneha , @davidgamero &  @qpetraroia  ❤️ cc: @squillace , @gambtho
**VSIX for quick test:** 
[vscode-kubernetes-tools-1.3.22-test.vsix.zip](https://github.com/user-attachments/files/19766483/vscode-kubernetes-tools-1.3.22-test.vsix.zip)
=> Publish release 1.3.22.

package.json, src/components/logs/app/main.js
Potential fix for [https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/security/code-scanning/5](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/security/code-scanning/5)
To fix the problem, we need to ensure that any user-provided data is properly sanitized or escaped before being rendered into the DOM. The best way to fix this issue without changing existing functionality is to use a library that provides contextual output encoding/escaping. One such library is `DOMPurify`, which can sanitize HTML and prevent XSS attacks.
We will sanitize the `contentToDisplay` variable before creating a contextual fragment and appending it to the DOM. This change will be made in the `render` function.
_Suggested fixes powered by Copilot Autofix. Review carefully before …
=> Potential fix for code scanning alert no. 5: Client-side cross-site scripting

src/kubectlUtils.ts, src/telemetry-helper.ts
This PR is to fix few scanning alerts agains this repo, so mainly the changes are to :
1. Ensures correct domain structure: 
- Matches `"azmk8s.io"` or `"azure.com"` **only when it appears as a full domain or subdomain** (e.g., `sub.azmk8s.io`, `xyz.azure.com`).  
- Prevents arbitrary words like `"maliciousazmk8s.io.evil.com"` from passing.  
2. Avoids partial matches inside strings:
- `"exampleazmk8s.io"` (will fail)
- `"abc.azmk8s.io"` (will succeed)
Thanks heaps, fyi @ReinierCC , @tejhan, @bosesuneha, @qpetraroia , @squillace, @davidgamero
=> Fix some scanning alerts.

src/components/logs/app/main.js
When viewing pod logs in the Webview:
- The **Scroll to Bottom** button is inconsistent and fails once logs exceed the pagination threshold.  
- Manually scrolling enters an infinite‐load loop and never actually reaches the end.
Observed behavior: 
https://github.com/user-attachments/assets/320fa605-328e-4d76-923f-e8661ff2569b
Fixed behavior: 
https://github.com/user-attachments/assets/1249c9e0-f46e-4632-9c3f-da9c6b94e8cf
Fixes issues: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1368, https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1226, https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1220 & https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1135
Reintroduced a refactored …
=> [Fix] Broken behavior when viewing large pod logs in webview

src/extension.ts
This PR fixes an issue where setting a new kubeconfig via the context menu would throw an error. The root cause was outdated logic that attempted to handle arbitrary contextual arguments passed by older versions of VS Code. This logic is no longer necessary and was interfering with expected behavior—specifically, it failed to properly differentiate between a context object and a valid kubeconfig path. The function has been updated to safely ignore irrelevant contextual arguments and prevent this error.
**Observed behavior**
https://github.com/user-attachments/assets/a0af1553-c29e-4342-b042-00026c686192
**Fixes Issues**
- #1509
- https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1115
.vsix for testing: [vscode-kubernetes-tools-1.3.22-kubeconfigfix.vsix.zip](https://g …
=> [Fix] Error with 'Set kubeconfig'

.github/workflows/close-stale-prs.yml
Hiya, intent of this PR is to add auto closure of inactive pull requests
This PR adds a scheduled GitHub Actions workflow that automatically closes open pull requests that have been inactive for more than 3 months.
- Runs `daily at 2:00 AM UTC`.
- Checks all open pull requests.
- If a PR hasn't been updated in the last **90+ days**:
- Adds a comment explaining the closure.
- Closes the PR to keep the repository clean and active.
- This helps reduce stale PRs and maintain focus on active contributions.
- Closed PRs can always be **reopened later** if needed!
Thanks heaps and gently fyi to @tejhan, @ReinierCC , @bosesuneha , @davidgamero and fyi to @squillace + @gambtho <3
=> Add bot for stale PR closure

package-lock.json, package.json, src/components/cloudprovider/aksprovider.ts, src/extension.ts
This PR serves to fix the implementation for adding an existing cluster, now allowing users to properly add AKS clusters to their kubeconfig & interactable cluster tree in the extension.
The functionality for adding an existing cluster was not working as expected, likely due to older code / deprecated packages. Included below is documentation of observed broken behavior & new implementation for easy reference.
**Observed Behavior**
https://github.com/user-attachments/assets/cb984cf4-2e2d-477d-a91c-cb5253f4e18a
**New Behavior** 
https://github.com/user-attachments/assets/e4b97f72-3a6a-4c4f-9df3-a715630b2e92
**.vsix for testing:** [vscode-kubernetes-tools-1.3.22-addexistingcluster.vsix.zip](https://github.com/user-attachments/files/19817289/vscode-kubernetes-tools-1.3.22-addexistingcluster.v …
=> Add existing cluster [Fix]

src/components/webpanel/webpanel.ts
This PR enables built-in `Ctrl + F` search in the Logs Webview by setting `enableFindWidget` to `true`. This helps users out with an additional tool to assist when investigating logs in the webview. 
Related issues: 
- https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1196
- https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1241
.vsix: [vscode-kubernetes-tools-1.3.23-find.vsix.zip](https://github.com/user-attachments/files/20108314/vscode-kubernetes-tools-1.3.23-find.vsix.zip)
=> Enabling search functionality in Log Webviews

src/extension.ts
When users switch machines, their kubeconfig file paths come with them through their VS Code settings. If a path doesn’t exist on the new machine, there's currently no feedback — the clusters view just stays empty. This can confuse users into thinking their kubeconfig is broken or that something else in the extension isn’t working, which a few users have reported.
This update shows a clear message when a selected kubeconfig file is missing, and also provides a button to easily remove the invalid path from the user’s known kubeconfigs.
Fixes issue: 
- https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1237 
.vsix: [vscode-kubernetes-tools-1.3.23-testkc.vsix.zip](https://github.com/user-attachments/files/20106725/vscode-kubernetes-tools-1.3.23-testkc.vsix.zip)
=> Adding check for kubeconfig file path existence

package-lock.json, package.json, src/explainer.ts
This work is for removing decprecated `request` package and replace it with `node-fetch`, intern this will help in fixing: https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/security/dependabot/18 and https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/security/dependabot/17 
Thanks heaps and gentle fyi to @tejhan and @squillace ❤️ 
I have tested this change in my local and it had no adverse effect into existing aspect, but in longer run we should think of re-accessing the need of explainer.ts and might be our yaml extension dependency is enough to handle the help hover text.
Thank you so much and here is vsix for playing around.
[vscode-kubernetes-tools-1.3.23-test-pkg-deprecation.vsix.zip](https://github.com/user-attachments/files/20377654/vscode-kubernetes …
=> Work to remove deprecated request package.

src/helm.funcmap.ts
This PR adds support for the `kebabcase` template function to the Helm linter, enabling proper recognition, IntelliSense, & hover documentation.
Fixes issue: 
- https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1544
.vsix: [vscode-kubernetes-tools-1.3.23-kebabtest.vsix.zip](https://github.com/user-attachments/files/20592437/vscode-kubernetes-tools-1.3.23-kebabtest.vsix.zip)
=> Adding kebabcase template function to helm linter

CHANGELOG.md, package-lock.json, package.json
This PR is intended to open release for version `1.13.24` which carries following key things along with various dependant PR.
* Dependabot PRs
* Alignment and visual feedback fixes (#1527)
* Enabling find widget (#1536)
* Add check for kconfig file path existence (#1535)
* Add project CNCF logo for this project. (#1537)
* Update vscode engine and pacakge. (#1538)
* Remove invalid badge. (#1550)
* Removing deprecated download package (#1515)
* Work to remove deprecated request package. (#1552)
* fixing gotemplate block comments for toggleability (#1566)
* Added kebabcase recognition to linter (#1565)
* updating tar-fs & removing request package (#1575)
Thanks heaps, and ❤️ gentle fyi to (Lets please get this quick spin around windows and other O/S please)  @ReinierCC, @tejhan, @bosesuneha …
=> Publish release 1.3.24

snippets/ingress.yaml, snippets/pod.yaml
This PR updates the Kubernetes manifest snippets to use the <a target="_blank" href ="https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/"> recommended metadata label conventions</a>, specifically those prefixed with `app.kubernetes.io/`.
Closes issue:
- https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1479
fyi @Tatsinnit
=> Use recommended Kubernetes metadata labels in snippets

CHANGELOG.md, package-lock.json, package.json
This PR is intended to open release for version `1.13.25` which carries following key things along with various dependant PR.
* Dependabot PRs
* Use recommended Kubernetes metadata labels in snippets (#1577)
* Fixing duplicate detection & adding overwrite option (#1564)
* Adding check & replacement option for invalid active kubeconfig (#1567)
Thanks heaps, and ❤️ gentle fyi to (Lets please get this quick spin around windows and other O/S please)  @ReinierCC, @tejhan, @bosesuneha , @davidgamero &  @qpetraroia  ❤️ cc: @squillace , @gambtho
Please note we are aiming for midweek or end of this week release, thanks.
**VSIX for quick test:** 
[vscode-kubernetes-tools-1.3.25-test.vsix.zip](https://github.com/user-attachments/files/21009942/vscode-kubernetes-tools-1.3.25-test.vsix.zip)
=> Publish version 1.3.25

src/components/installer/installationlayout.ts
This PR fixes a bug where some Mac devices running under Rosetta (like M3 for example) were being seen as x64 via the `process.arch` function, causing the amd64 binary to be installed and fail at runtime. We now use `uname -m` on macOS to get the true architecture and ensure arm64 builds go to arm64 devices. It seems that some users had the incorrect binary silently installed, which causes a couple related errors. 
Addresses issue: 
- https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1360
.vsix: [vscode-kubernetes-tools-1.3.24-arch1.vsix.zip](https://github.com/user-attachments/files/21022357/vscode-kubernetes-tools-1.3.24-arch1.vsix.zip)
=> Detect real CPU arch on macOS to install correct binary

src/components/config/config.ts, src/helm.exec.ts
Users have reported receiving dependency alerts for tools they don’t use. This PR is part of a series of a couple smaller pr's to tackle a group of similar issues reported related to binary tooling, and in this case we need to have clear disable options at each binary tool’s discovery point & prevent premature invocation of tool discovery, alongside other niche errors and cases which will later be addressed as well.
This change adds a second action to the Helm-not-found notification to Disable Helm checks, essentially a “Do not notify again” button so non-Helm users can suppress future Helm checks without having to look for and edit specific JSON config settings manually.
Addresses issue:
- https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/issues/1252
.vsix: …
=> Adding option to disable unwanted Helm notifications
